import type { TeamUploadFile } from "../../db/schema";
import { deleteUploadedFile, downloadUploadedFile, isGcsConfigured, uploadFile } from "../gcs";

/**
 * Where an uploaded file's bytes live.
 *
 * Small files go in the row. A team's data log can be tens of megabytes, which
 * Postgres would hold but should not, so anything over the line goes to Cloud
 * Storage. When Cloud Storage is not configured (a dev box without the Google
 * keys) a large file is refused with a message that says so, rather than being
 * silently dropped or wedged into the database.
 */

/** Bytes up to here are kept in the row, so a dev box needs no cloud storage. */
export const INLINE_LIMIT = 8 * 1024 * 1024;

/** Largest single file the portal accepts. A full match data log fits inside this. */
export const MAX_FILE_BYTES = 128 * 1024 * 1024;

/** Largest one submission, across every file in it. */
export const MAX_UPLOAD_BYTES = 256 * 1024 * 1024;

/** Most files in one submission. A team hands over a handful, not a directory. */
export const MAX_FILES_PER_UPLOAD = 25;

export class UploadTooLargeError extends Error {}

export interface StoredBytes {
	content: string | null;
	gcs_path: string | null;
}

function gcsKey(uploadId: string, fileId: string, path: string): string {
	const safe = path.replace(/[^a-zA-Z0-9._-]+/g, "_").slice(-80);
	return `${uploadId}/${fileId}-${safe}`;
}

/**
 * Put bytes somewhere durable. `fileId` is generated by the caller so the key
 * is known before the row exists.
 */
export async function storeBytes(
	uploadId: string,
	fileId: string,
	path: string,
	data: Uint8Array,
): Promise<StoredBytes> {
	if (data.byteLength > MAX_FILE_BYTES) {
		throw new UploadTooLargeError(
			`${path} is larger than the ${Math.round(MAX_FILE_BYTES / 1024 / 1024)} MB limit.`,
		);
	}
	if (data.byteLength <= INLINE_LIMIT) {
		return { content: Buffer.from(data).toString("base64"), gcs_path: null };
	}
	if (!isGcsConfigured()) {
		throw new UploadTooLargeError(
			`${path} is ${Math.round(data.byteLength / 1024 / 1024)} MB. Files over ${Math.round(INLINE_LIMIT / 1024 / 1024)} MB need cloud storage, which is not configured on this server.`,
		);
	}
	const key = gcsKey(uploadId, fileId, path);
	await uploadFile(Buffer.from(data), key);
	return { content: null, gcs_path: key };
}

/** Read a file's bytes back, from wherever they went. */
export async function loadBytes(file: Pick<TeamUploadFile, "content" | "gcs_path">): Promise<Uint8Array> {
	if (file.content != null) return new Uint8Array(Buffer.from(file.content, "base64"));
	if (file.gcs_path) return new Uint8Array(await downloadUploadedFile(file.gcs_path));
	return new Uint8Array(0);
}

/** Drop the stored object for a file. The row itself goes by cascade. */
export async function deleteBytes(file: Pick<TeamUploadFile, "gcs_path">): Promise<void> {
	if (!file.gcs_path) return;
	try {
		await deleteUploadedFile(file.gcs_path);
	} catch (err) {
		// The row is going away either way; a stranded object is not worth failing on.
		console.error("[uploads] could not delete stored object", file.gcs_path, err);
	}
}
