import type { TeamUploadFile } from "../../db/schema";
import { deleteUploadedFile, downloadUploadedFile, isGcsConfigured, uploadFile } from "../gcs";

/**
 * Where an uploaded file's bytes live: Cloud Storage, all of them.
 *
 * Logs are large and there are a lot of them, so none of this belongs in
 * Postgres. If the bucket is not configured the upload is refused outright
 * rather than quietly kept somewhere else, because a file that landed in a
 * place nobody looks is worse than an upload that failed loudly.
 */

/** Largest single file we accept. A full match data log fits well inside this. */
export const MAX_FILE_BYTES = 256 * 1024 * 1024;

/** Largest one submission, across every file in it. */
export const MAX_UPLOAD_BYTES = 512 * 1024 * 1024;

/** Most files in one submission. A team hands over a handful, not a directory. */
export const MAX_FILES_PER_UPLOAD = 25;

export class UploadTooLargeError extends Error {}

export interface StoredBytes {
	/** Always null now. The column goes when the branch merges. */
	content: null;
	gcs_path: string;
}

function gcsKey(uploadId: string, fileId: string, path: string): string {
	const safe = path.replace(/[^a-zA-Z0-9._-]+/g, "_").slice(-80);
	return `${uploadId}/${fileId}-${safe}`;
}

/**
 * Put bytes in the bucket. `fileId` is generated by the caller so the object
 * key is known before the row exists.
 */
export async function storeBytes(
	uploadId: string,
	fileId: string,
	path: string,
	data: Uint8Array,
): Promise<StoredBytes> {
	if (data.byteLength > MAX_FILE_BYTES) {
		throw new UploadTooLargeError(
			`${path} is larger than the ${Math.round(MAX_FILE_BYTES / 1024 / 1024)} MB limit.`,
		);
	}
	if (!isGcsConfigured()) {
		throw new UploadTooLargeError(
			"Cloud storage is not configured on this server, so uploaded files have nowhere to go.",
		);
	}
	const key = gcsKey(uploadId, fileId, path);
	await uploadFile(Buffer.from(data), key);
	return { content: null, gcs_path: key };
}

/** Read a file's bytes back out of the bucket. */
export async function loadBytes(file: Pick<TeamUploadFile, "gcs_path">): Promise<Uint8Array> {
	if (!file.gcs_path) return new Uint8Array(0);
	return new Uint8Array(await downloadUploadedFile(file.gcs_path));
}

/** Drop the stored object for a file. The row itself goes by cascade. */
export async function deleteBytes(file: Pick<TeamUploadFile, "gcs_path">): Promise<void> {
	if (!file.gcs_path) return;
	try {
		await deleteUploadedFile(file.gcs_path);
	} catch (err) {
		// The row is going away either way; a stranded object is not worth failing on.
		console.error("[uploads] could not delete stored object", file.gcs_path, err);
	}
}
