import { asc, eq } from "drizzle-orm";
import { existsSync, mkdirSync } from "fs";
import jsPDF from "jspdf";
import { formatTimeShortNoAgoMinutes } from "../../shared/formatTime";
import { Profile } from "../../shared/types";
import { db } from "../db/db";
import { messages, notes } from "../db/schema";

const PAGE_W = 216; // letter mm
const PAGE_H = 279;
const ML = 14; // margin left
const MR = 14; // margin right
const MT = 16; // margin top
const MB = 16; // margin bottom
const USABLE_W = PAGE_W - ML - MR;
const BOTTOM_LIMIT = PAGE_H - MB - 10; // leave room for footer

function authorName(val: unknown): string {
	if (!val) return "unknown";
	if (typeof val === "object" && val !== null && "username" in val) return (val as any).username;
	return "unknown";
}

function fmtMs(ms: number | null | undefined): string {
	if (!ms || ms <= 0) return "-";
	return formatTimeShortNoAgoMinutes(ms) ?? "-";
}

function fmtDate(d: Date | string | null | undefined): string {
	if (!d) return "-";
	const dt = d instanceof Date ? d : new Date(d);
	return dt.toLocaleString("en-US", {
		month: "short",
		day: "numeric",
		hour: "numeric",
		minute: "2-digit",
		hour12: true,
	});
}

function humanizeStatus(s: string | null | undefined): string {
	if (!s) return "";
	switch (s) {
		case "Open":
			return "Open";
		case "Resolved":
			return "Resolved";
		case "NotApplicable":
			return "N/A";
		default:
			return s;
	}
}

function humanizeLevel(l: string | null | undefined): string {
	if (!l || l === "None") return "";
	return l;
}

function humanizeIssueType(value: string | null | undefined): string {
	if (!value) return "";
	const map: Record<string, string> = {
		RoboRioIssue: "roboRIO Issue",
		DSIssue: "Driver Station Issue",
		NoRobot: "No Robot",
		RadioIssue: "Radio Issue",
		RobotPwrIssue: "Power Issue",
		OtherRobotIssue: "Robot Issue",
		VenueIssue: "Venue Issue",
		ElectricalIssue: "Electrical Issue",
		MechanicalIssue: "Mechanical Issue",
		VolunteerIssue: "Volunteer Issue",
		Other: "Other",
	};
	return map[value] ?? value;
}

export async function generateNotesReportPdf(eventCode: string, eventName: string): Promise<string> {
	// ── load data ────────────────────────────────────────────────────────────
	const allNotes = await db
		.select()
		.from(notes)
		.where(eq(notes.event_code, eventCode))
		.orderBy(asc(notes.team), asc(notes.created_at))
		.execute();

	const allMessages = await db
		.select()
		.from(messages)
		.where(eq(messages.event_code, eventCode))
		.orderBy(asc(messages.created_at))
		.execute();

	const msgByNote = new Map<string, typeof allMessages>();
	for (const m of allMessages) {
		if (!msgByNote.has(m.note_id)) msgByNote.set(m.note_id, []);
		msgByNote.get(m.note_id)!.push(m);
	}

	// group notes by team (null → event/match notes)
	const teamGroups = new Map<string, typeof allNotes>();
	for (const n of allNotes) {
		const key = n.team != null ? String(n.team) : "__event__";
		if (!teamGroups.has(key)) teamGroups.set(key, []);
		teamGroups.get(key)!.push(n);
	}

	// sort: numeric team numbers first (ascending), then event/match notes
	const sortedKeys = Array.from(teamGroups.keys()).sort((a, b) => {
		if (a === "__event__") return 1;
		if (b === "__event__") return -1;
		return parseInt(a) - parseInt(b);
	});

	// ── PDF setup ────────────────────────────────────────────────────────────
	const doc = new jsPDF({ format: "letter", unit: "mm" });
	let y = MT;
	let pageNum = 1;

	function addPage() {
		doc.addPage();
		pageNum++;
		y = MT;
		drawPageFooter();
	}

	function drawPageFooter() {
		const py = PAGE_H - 8;
		doc.setFontSize(8);
		doc.setTextColor("#888888");
		doc.text(eventCode, PAGE_W / 2, py, { align: "center" });
		doc.text(`Generated by FTA Buddy`, PAGE_W - MR, py - 4, { align: "right" });
		doc.text(new Date().toLocaleString(), PAGE_W - MR, py, { align: "right" });
		doc.setTextColor("#000000");
	}

	function ensureSpace(needed: number) {
		if (y + needed > BOTTOM_LIMIT) addPage();
	}

	function textWrapped(
		text: string,
		x: number,
		width: number,
		fontSize: number,
		color: string,
		bold = false,
	): number {
		doc.setFontSize(fontSize);
		doc.setTextColor(color);
		doc.setFont("helvetica", bold ? "bold" : "normal");
		const lines = doc.splitTextToSize(text, width) as string[];
		const lh = fontSize * 0.4;
		for (const line of lines) {
			ensureSpace(lh + 1);
			doc.text(line, x, y);
			y += lh + 0.5;
		}
		return lines.length;
	}

	// ── Title ────────────────────────────────────────────────────────────────
	doc.setFontSize(18);
	doc.setFont("helvetica", "bold");
	doc.setTextColor("#000000");
	doc.text(`Notes Report: ${eventName}`, ML, y);
	y += 8;

	doc.setFontSize(9);
	doc.setFont("helvetica", "normal");
	doc.setTextColor("#555555");
	doc.text(`${allNotes.length} notes total · Generated ${new Date().toLocaleString()}`, ML, y);
	y += 5;
	doc.setDrawColor("#cccccc");
	doc.line(ML, y, PAGE_W - MR, y);
	y += 6;

	drawPageFooter();

	// ── Per-team sections ────────────────────────────────────────────────────
	for (const key of sortedKeys) {
		const teamNotes = teamGroups.get(key)!;
		const teamLabel = key === "__event__" ? "Event / Match Notes" : `Team ${key}`;

		// Stats for team
		let totalOpenMs = 0;
		let closedCount = 0;
		for (const n of teamNotes) {
			if (n.created_at && n.closed_at) {
				totalOpenMs += new Date(n.closed_at).getTime() - new Date(n.created_at).getTime();
				closedCount++;
			}
		}
		const avgOpenMs = closedCount > 0 ? totalOpenMs / closedCount : null;
		const openCount = teamNotes.filter((n) => n.resolution_status === "Open").length;
		const resolvedCount = teamNotes.filter((n) => n.resolution_status === "Resolved").length;

		ensureSpace(16);

		// Team header bar
		doc.setFillColor("#1e40af");
		doc.rect(ML, y - 4, USABLE_W, 9, "F");
		doc.setFontSize(11);
		doc.setFont("helvetica", "bold");
		doc.setTextColor("#ffffff");
		doc.text(teamLabel, ML + 2, y + 2.5);
		y += 7;

		// Stats line
		doc.setFontSize(8);
		doc.setFont("helvetica", "normal");
		doc.setTextColor("#333333");
		const statsLine = [
			`${teamNotes.length} note${teamNotes.length !== 1 ? "s" : ""}`,
			openCount > 0 ? `${openCount} open` : null,
			resolvedCount > 0 ? `${resolvedCount} resolved` : null,
			totalOpenMs > 0 ? `Total open time: ${fmtMs(totalOpenMs)}` : null,
			avgOpenMs != null ? `Avg: ${fmtMs(avgOpenMs)}` : null,
		]
			.filter(Boolean)
			.join("  ·  ");
		doc.text(statsLine, ML, y);
		y += 5;

		// ── Per-note cards ──────────────────────────────────────────────────
		for (const note of teamNotes) {
			const noteMessages = msgByNote.get(note.id) ?? [];
			const openTimeMs =
				note.created_at && note.closed_at
					? new Date(note.closed_at).getTime() - new Date(note.created_at).getTime()
					: null;

			const levelStr = humanizeLevel(note.tournament_level);
			const matchStr =
				note.match_number != null
					? `${levelStr ? levelStr + " " : ""}Match ${note.match_number}${note.play_number != null && note.play_number > 1 ? ` P${note.play_number}` : ""}`
					: null;

			// card top rule
			ensureSpace(20);
			doc.setDrawColor("#dddddd");
			doc.line(ML, y, PAGE_W - MR, y);
			y += 3;

			// note text (full, wrapped)
			textWrapped(note.text || "(no text)", ML + 2, USABLE_W - 4, 9.5, "#111111", true);
			y += 1;

			// metadata row 1: type | status | issue | match
			const meta1Parts = [
				`Type: ${note.note_type === "TeamIssue" ? "Team Issue" : note.note_type === "EventNote" ? "Event Note" : "Match Note"}`,
				`Status: ${humanizeStatus(note.resolution_status)}`,
				note.issue_type ? `Issue: ${humanizeIssueType(note.issue_type)}` : null,
				matchStr ? `Match: ${matchStr}` : null,
			]
				.filter(Boolean)
				.join("   ");

			doc.setFontSize(8);
			doc.setFont("helvetica", "normal");
			doc.setTextColor("#555555");
			ensureSpace(5);
			doc.text(meta1Parts, ML + 2, y);
			y += 4;

			// metadata row 2: opened, closed, open time, author, assigned
			const meta2Parts = [
				`Opened: ${fmtDate(note.created_at)}`,
				note.closed_at ? `Closed: ${fmtDate(note.closed_at)}` : "Open",
				openTimeMs ? `Open time: ${fmtMs(openTimeMs)}` : null,
				`Author: ${authorName(note.author)}`,
				note.assigned_to ? `CSA: ${authorName(note.assigned_to)}` : null,
				note.resolved_by ? `Resolved by: ${authorName(note.resolved_by)}` : null,
			]
				.filter(Boolean)
				.join("   ");

			doc.setFontSize(8);
			doc.setTextColor("#555555");
			ensureSpace(5);
			doc.text(meta2Parts, ML + 2, y);
			y += 4;

			// messages
			if (noteMessages.length > 0) {
				ensureSpace(5);
				doc.setFontSize(8);
				doc.setFont("helvetica", "bold");
				doc.setTextColor("#333333");
				doc.text(`Messages (${noteMessages.length}):`, ML + 4, y);
				y += 3.5;

				for (const msg of noteMessages) {
					const header = `${authorName(msg.author)}  ·  ${fmtDate(msg.created_at)}`;
					ensureSpace(8);
					doc.setFontSize(7.5);
					doc.setFont("helvetica", "bold");
					doc.setTextColor("#444444");
					doc.text(header, ML + 6, y);
					y += 3.5;
					textWrapped(msg.text || "", ML + 6, USABLE_W - 8, 8, "#222222");
					y += 1;
				}
			}

			y += 3;
		}

		y += 4;
	}

	// ── Save ─────────────────────────────────────────────────────────────────
	if (!existsSync("/data/reports")) mkdirSync("/data/reports", { recursive: true });
	const filePath = `/data/reports/NotesReport-${eventCode}.pdf`;
	doc.save(filePath);
	return `/report/NotesReport-${eventCode}.pdf`;
}
