import { existsSync, mkdirSync } from 'fs';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportFormat {
    title: string;
    description: string;
    headers: string[];
    fileName: string;
}

export async function generateReport(format: ReportFormat, data: (string | number)[][], eventCode: string) {
    const doc = new jsPDF({
        format: 'letter'
    });
    doc.setFontSize(20);
    doc.text(format.title, 15, 20);
    doc.setFontSize(12);
    doc.text(format.description, 15, 30);

    autoTable(doc, {
        head: [format.headers],
        body: data,
        startY: 40,
        margin: { top: 10, bottom: 20 },
    });

    const date = new Date();
    const formattedDate = `${date.toLocaleDateString()} ${date.toLocaleTimeString()}`;
    doc.setFontSize(10);
    doc.setTextColor('#666666');
    const pageCount = doc.internal.pages.length;
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`${eventCode}`, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 12, { align: 'center' });
        doc.text(`Generated by FTA Buddy`, doc.internal.pageSize.width - 10, doc.internal.pageSize.height - 15, { align: 'right' });
        doc.text(formattedDate, doc.internal.pageSize.width - 10, doc.internal.pageSize.height - 10, { align: 'right' });
    }

    if (!existsSync('reports')) {
        mkdirSync('reports');
    }

    await doc.save(`reports/${format.fileName}-${eventCode}.pdf`);
    return `/report/${format.fileName}-${eventCode}.pdf`;
}