// Status light help: CTRE devices. See shared.ts for the step rules.

import { type StatusLightHelp, CAN_WIRING_STEPS, CTRE_BOOTLOADER_STEPS, CTRE_CANCODER, CTRE_CANDLE, CTRE_CANIVORE, CTRE_CANRANGE, CTRE_DAMAGED_STEPS, CTRE_FX, CTRE_FXS, CTRE_PCM, CTRE_PDP, CTRE_PIGEON, CTRE_SRX, CTRE_VSPX, PHOENIX_NOT_RUNNING_STEPS } from "./shared";

export const ctreHelp = {
	"ctretalonfx.disabled-codes.no-power": {
		device: "Talon FX",
		led: "Status",
		state: "Both off",
		meaning: "No 12 V on the V+ and V- leads.",
		steps: [
			"Check the breaker on that PDP or PDH channel.",
			"Check the crimp or connector at the PDP or PDH and at the device.",
			{ kind: "check", text: "Are both LEDs still off?", yes: "Swap the power leads.", no: "Problem solved." },
		],
		source: CTRE_FX,
	},
	"ctretalonfx.disabled-codes.valid-can-pwm-signal-robot-is-disabled-phoenix-is-running": {
		device: "Talon FX",
		led: "Status",
		state: "Both blink orange together",
		meaning: "CAN is good, Phoenix is running, and the robot is disabled. Normal.",
		source: CTRE_FX,
	},
	"ctretalonfx.disabled-codes.valid-can-pwm-phoenix-is-not-detected": {
		device: "Talon FX",
		led: "Status",
		state: "Alternating orange",
		meaning:
			"The CAN bus is fine but no Phoenix based robot program is talking to it. Code is not running, crashed, or does not create this device.",
		steps: PHOENIX_NOT_RUNNING_STEPS,
		source: CTRE_FX,
	},
	"ctretalonfx.disabled-codes.invalid-can-pwm-signal": {
		device: "Talon FX",
		led: "Status",
		state: "Alternating red",
		meaning: "No valid CAN or PWM signal.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_FX,
	},
	"ctretalonfx.enabled-codes.enabled-with-neutral-output": {
		device: "Talon FX",
		led: "Status",
		state: "Both solid orange",
		meaning: "Enabled with zero output. Normal.",
		steps: [
			{ kind: "check", text: "Should it be moving?", yes: "Continue.", no: "Problem solved." },
			"Check the joystick in the DS and the code for a zero command.",
		],
		source: CTRE_FX,
	},
	"ctretalonfx.enabled-codes.driving-in-reverse-rate-dutycycle": {
		device: "Talon FX",
		led: "Status",
		state: "Both blink red together",
		meaning: "Driving in reverse. Blink rate follows duty cycle.",
		source: CTRE_FX,
	},
	"ctretalonfx.enabled-codes.driving-in-forward-rate-dutycycle": {
		device: "Talon FX",
		led: "Status",
		state: "Both blink green together",
		meaning: "Driving forward. Blink rate follows duty cycle.",
		source: CTRE_FX,
	},
	"ctretalonfx.enabled-codes.talon-limited-offset-direction-forward-reverse": {
		device: "Talon FX",
		led: "Status",
		state: "Offset red and off",
		meaning:
			"A hard or soft limit is engaged. The offset direction shows which one. Output in that direction is blocked.",
		steps: [
			"Check the limit switch wiring. A disconnected normally closed switch reads as pressed.",
			"Check the soft limit and limit switch config in Phoenix Tuner X.",
			"Move the mechanism off the limit.",
			{ kind: "check", text: "Still on the limit with nothing pressing the switch?", yes: "Replace the limit switch.", no: "Problem solved." },
		],
		source: CTRE_FX,
	},
	"ctretalonfx.special-codes.thermal-cutoff-warning": {
		device: "Talon FX",
		led: "Status",
		state: "Offset orange and off",
		meaning: "The motor or controller is too hot. Output is reduced or cut.",
		steps: [
			"Let it cool.",
			"Check for a stalled or binding mechanism.",
			"Have the team add stator current limits.",
		],
		source: CTRE_FX,
	},
	"ctretalonfx.special-codes.using-pro-command-without-license": {
		device: "Talon FX",
		led: "Status",
		state: "Alternating red and green",
		meaning: "Code sent a Phoenix Pro only control request to an unlicensed device. The request is ignored.",
		steps: ["License the device in Phoenix Tuner X, or change the code to a non-Pro control request."],
		source: CTRE_FX,
	},
	"ctretalonfx.special-codes.damaged-hardware": {
		device: "Talon FX",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: [
			"Confirm with Self Test in Phoenix Tuner X.",
			"Do not run it. Reverse power or a shorted output is the usual cause.",
			"Check the wiring polarity before fitting the replacement.",
			"Swap the motor. On a Kraken or Falcon the Talon FX is built in, so you replace the whole motor.",
		],
		source: CTRE_FX,
	},
	"ctretalonfx.special-codes.in-bootloader-field-upgrade-in-tuner-x": {
		device: "Talon FX",
		led: "Status",
		state: "One LED alternates green and orange",
		meaning:
			"The device is in its bootloader with no application firmware. It will not respond to control until firmware is loaded.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_FX,
	},
	"ctretalonfxs.disabled-codes.no-power": {
		device: "Talon FXS",
		led: "Status",
		state: "Both off",
		meaning: "No 12 V on the V+ and V- leads.",
		steps: [
			"Check the breaker on that PDP or PDH channel.",
			"Check the crimp or connector at the PDP or PDH and at the device.",
			{ kind: "check", text: "Are both LEDs still off?", yes: "Swap the power leads.", no: "Problem solved." },
		],
		source: CTRE_FXS,
	},
	"ctretalonfxs.disabled-codes.valid-can-pwm-signal-robot-is-disabled-phoenix-is-running": {
		device: "Talon FXS",
		led: "Status",
		state: "Both blink orange together",
		meaning: "CAN is good, Phoenix is running, and the robot is disabled. Normal.",
		source: CTRE_FXS,
	},
	"ctretalonfxs.disabled-codes.valid-can-pwm-phoenix-is-not-detected": {
		device: "Talon FXS",
		led: "Status",
		state: "Alternating orange",
		meaning:
			"The CAN bus is fine but no Phoenix based robot program is talking to it. Code is not running, crashed, or does not create this device.",
		steps: PHOENIX_NOT_RUNNING_STEPS,
		source: CTRE_FXS,
	},
	"ctretalonfxs.disabled-codes.invalid-can-pwm-signal": {
		device: "Talon FXS",
		led: "Status",
		state: "Alternating red",
		meaning: "No valid CAN or PWM signal.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_FXS,
	},
	"ctretalonfxs.enabled-codes.enabled-with-neutral-output": {
		device: "Talon FXS",
		led: "Status",
		state: "Both solid orange",
		meaning: "Enabled with zero output. Normal.",
		steps: [
			{ kind: "check", text: "Should it be moving?", yes: "Continue.", no: "Problem solved." },
			"Check the joystick in the DS and the code for a zero command.",
		],
		source: CTRE_FXS,
	},
	"ctretalonfxs.enabled-codes.driving-in-reverse-rate-dutycycle": {
		device: "Talon FXS",
		led: "Status",
		state: "Both blink red together",
		meaning: "Driving in reverse. Blink rate follows duty cycle.",
		source: CTRE_FXS,
	},
	"ctretalonfxs.enabled-codes.driving-in-forward-rate-dutycycle": {
		device: "Talon FXS",
		led: "Status",
		state: "Both blink green together",
		meaning: "Driving forward. Blink rate follows duty cycle.",
		source: CTRE_FXS,
	},
	"ctretalonfxs.enabled-codes.talon-limited-offset-direction-forward-reverse": {
		device: "Talon FXS",
		led: "Status",
		state: "Offset red and off",
		meaning:
			"A hard or soft limit is engaged. The offset direction shows which one. Output in that direction is blocked.",
		steps: [
			"Check the limit switch wiring. A disconnected normally closed switch reads as pressed.",
			"Check the soft limit and limit switch config in Phoenix Tuner X.",
			"Move the mechanism off the limit.",
			{ kind: "check", text: "Still on the limit with nothing pressing the switch?", yes: "Replace the limit switch.", no: "Problem solved." },
		],
		source: CTRE_FXS,
	},
	"ctretalonfxs.special-codes.thermal-cutoff-warning": {
		device: "Talon FXS",
		led: "Status",
		state: "Offset orange and off",
		meaning: "Thermal cutoff, or the temperature sensor is missing. Output is reduced or cut.",
		steps: [
			"Brushless motor: reseat the JST sensor cable and check it for damage. Confirm the motor type in Tuner X matches the motor.",
			"Brushed motor: confirm the brushed motor option is selected in Tuner X.",
			"Let it cool. Have the team add stator current limits.",
		],
		source: CTRE_FXS,
	},
	"ctretalonfxs.special-codes.using-pro-command-without-license": {
		device: "Talon FXS",
		led: "Status",
		state: "Alternating red and green",
		meaning: "Code sent a Phoenix Pro only control request to an unlicensed device. The request is ignored.",
		steps: ["License the device in Phoenix Tuner X, or change the code to a non-Pro control request."],
		source: CTRE_FXS,
	},
	"ctretalonfxs.special-codes.damaged-hardware": {
		device: "Talon FXS",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_FXS,
	},
	"ctretalonfxs.special-codes.in-bootloader-field-upgrade-in-tuner-x": {
		device: "Talon FXS",
		led: "Status",
		state: "One LED alternates green and orange",
		meaning:
			"The device is in its bootloader with no application firmware. It will not respond to control until firmware is loaded.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_FXS,
	},
	"ctretalonsrx.calibration-codes.calibration-in-progress": {
		device: "Talon SRX",
		led: "Status",
		state: "Flashing red and green",
		meaning: "PWM calibration mode. Someone held the B/C CAL button. Only matters for PWM control.",
		steps: [
			{ kind: "check", text: "Is this robot controlled over CAN?", yes: "Ignore it, PWM calibration does nothing.", no: "Continue." },
			"Release the B/C CAL button.",
			{ kind: "check", text: "Still flashing red and green?", yes: "Power cycle the controller.", no: "Problem solved." },
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.calibration-codes.successful-calibration": {
		device: "Talon SRX",
		led: "Status",
		state: "Blinking green",
		meaning: "PWM calibration succeeded.",
		source: CTRE_SRX,
	},
	"ctretalonsrx.calibration-codes.failed-calibration": {
		device: "Talon SRX",
		led: "Status",
		state: "Blinking red",
		meaning: "PWM calibration failed. The previous calibration is kept.",
		steps: [
			"Power cycle the controller.",
			{ kind: "check", text: "Do you need PWM control on this robot?", yes: "Continue.", no: "Problem solved." },
			"Repeat the calibration with full stick travel.",
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.no-power": {
		device: "Talon SRX",
		led: "Status",
		state: "Both off",
		meaning: "No 12 V on the V+ and V- leads.",
		steps: [
			"Check the breaker on that PDP or PDH channel.",
			"Check the crimp or connector at the PDP or PDH and at the device.",
			{ kind: "check", text: "Are both LEDs still off?", yes: "Swap the power leads.", no: "Problem solved." },
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.driving-in-forward-rate-dutycycle": {
		device: "Talon SRX",
		led: "Status",
		state: "Both blink green",
		meaning: "Driving forward. Blink rate follows duty cycle.",
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.driving-in-reverse-rate-dutycycle": {
		device: "Talon SRX",
		led: "Status",
		state: "Both blink red",
		meaning: "Driving in reverse. Blink rate follows duty cycle.",
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.can-pwm-detected-robot-disabled": {
		device: "Talon SRX",
		led: "Status",
		state: "Alternating off and orange",
		meaning: "CAN or PWM signal present, robot disabled. Normal.",
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.can-pwm-not-detected": {
		device: "Talon SRX",
		led: "Status",
		state: "Alternating off and red",
		meaning: "No CAN bus or PWM signal detected.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.damaged-hardware": {
		device: "Talon SRX",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.forward-soft-hard-limit-triggered": {
		device: "Talon SRX",
		led: "Status",
		state: "Red strobe towards M+",
		meaning: "The forward limit switch or soft limit is active. Forward output is blocked.",
		steps: [
			"Check the limit switch wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"Check the limit switch and soft limit config in Phoenix Tuner.",
			"Move the mechanism off the limit.",
			{ kind: "check", text: "Still on the limit with nothing pressing the switch?", yes: "Replace the limit switch.", no: "Problem solved." },
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.reverse-soft-hard-limit-triggered": {
		device: "Talon SRX",
		led: "Status",
		state: "Red strobe towards M-",
		meaning: "The reverse limit switch or soft limit is active. Reverse output is blocked.",
		steps: [
			"Check the limit switch wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"Check the limit switch and soft limit config in Phoenix Tuner.",
			"Move the mechanism off the limit.",
			{ kind: "check", text: "Still on the limit with nothing pressing the switch?", yes: "Replace the limit switch.", no: "Problem solved." },
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.in-boot-loader": {
		device: "Talon SRX",
		led: "Status",
		state: "One LED alternates green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: [
			"Field-upgrade the firmware in Phoenix Tuner.",
			{ kind: "check", text: "Does it refuse the firmware?", yes: "Swap the device.", no: "Problem solved." },
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.normal-operation-codes.neutral-signal-applied-within-deadband": {
		device: "Talon SRX",
		led: "Status",
		state: "Both solid orange",
		meaning: "Enabled with zero output, or the command is inside the deadband. Normal.",
		steps: [
			{ kind: "check", text: "Should it be moving?", yes: "Continue.", no: "Problem solved." },
			"Check the joystick and the code for a zero command.",
		],
		source: CTRE_SRX,
	},
	"ctretalonsrx.b-c-cal-button-color-codes.brake-mode": {
		device: "Talon SRX",
		led: "B/C CAL button",
		state: "Solid red",
		meaning: "Brake mode. The motor shorts its leads when the output is neutral.",
		source: CTRE_SRX,
	},
	"ctretalonsrx.b-c-cal-button-color-codes.coast-mode": {
		device: "Talon SRX",
		led: "B/C CAL button",
		state: "Off",
		meaning: "Coast mode. The motor spins freely when the output is neutral.",
		source: CTRE_SRX,
	},
	"ctrevictorspx.calibration-codes.calibration-in-progress": {
		device: "Victor SPX",
		led: "Status",
		state: "Flashing red and green",
		meaning: "PWM calibration mode. Someone held the B/C CAL button. Only matters for PWM control.",
		steps: [
			{ kind: "check", text: "Is this robot controlled over CAN?", yes: "Ignore it, PWM calibration does nothing.", no: "Continue." },
			"Release the B/C CAL button.",
			{ kind: "check", text: "Still flashing red and green?", yes: "Power cycle the controller.", no: "Problem solved." },
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.calibration-codes.successful-calibration": {
		device: "Victor SPX",
		led: "Status",
		state: "Blinking green",
		meaning: "PWM calibration succeeded.",
		source: CTRE_VSPX,
	},
	"ctrevictorspx.calibration-codes.failed-calibration": {
		device: "Victor SPX",
		led: "Status",
		state: "Blinking red",
		meaning: "PWM calibration failed. The previous calibration is kept.",
		steps: [
			"Power cycle the controller.",
			{ kind: "check", text: "Do you need PWM control on this robot?", yes: "Continue.", no: "Problem solved." },
			"Repeat the calibration with full stick travel.",
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.no-power": {
		device: "Victor SPX",
		led: "Status",
		state: "Both off",
		meaning: "No 12 V on the V+ and V- leads.",
		steps: [
			"Check the breaker on that PDP or PDH channel.",
			"Check the crimp or connector at the PDP or PDH and at the device.",
			{ kind: "check", text: "Are both LEDs still off?", yes: "Swap the power leads.", no: "Problem solved." },
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.driving-in-forward-rate-dutycycle": {
		device: "Victor SPX",
		led: "Status",
		state: "Both blink green",
		meaning: "Driving forward. Blink rate follows duty cycle.",
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.driving-in-reverse-rate-dutycycle": {
		device: "Victor SPX",
		led: "Status",
		state: "Both blink red",
		meaning: "Driving in reverse. Blink rate follows duty cycle.",
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.can-pwm-detected-robot-disabled": {
		device: "Victor SPX",
		led: "Status",
		state: "Alternating off and orange",
		meaning: "CAN or PWM signal present, robot disabled. Normal.",
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.can-pwm-not-detected": {
		device: "Victor SPX",
		led: "Status",
		state: "Alternating off and slow red",
		meaning: "No CAN bus or PWM signal detected.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.fault-detected": {
		device: "Victor SPX",
		led: "Status",
		state: "Alternating off and fast red",
		meaning: "A fault is active on the controller.",
		steps: [
			"Run Self Test in Phoenix Tuner to read the fault.",
			"Check supply voltage at the controller. Let it cool if it is hot.",
			"Power cycle the controller.",
			{ kind: "check", text: "Still faulting with good power and no load?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.damaged-hardware": {
		device: "Victor SPX",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.forward-soft-hard-limit-triggered": {
		device: "Victor SPX",
		led: "Status",
		state: "Red strobe towards M+",
		meaning:
			"The forward limit switch or soft limit is active. Forward output is blocked. The Victor SPX has no data port, so the limit comes from a remote sensor or a soft limit in code.",
		steps: [
			"Check the remote limit source and soft limit config in Phoenix Tuner.",
			"Move the mechanism off the limit.",
			{ kind: "check", text: "Still blocked in that direction?", yes: "Continue.", no: "Problem solved." },
			"Have the team clear the soft limit or fix the remote sensor in code.",
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.reverse-soft-hard-limit-triggered": {
		device: "Victor SPX",
		led: "Status",
		state: "Red strobe towards M-",
		meaning:
			"The reverse limit switch or soft limit is active. Reverse output is blocked. The Victor SPX has no data port, so the limit comes from a remote sensor or a soft limit in code.",
		steps: [
			"Check the remote limit source and soft limit config in Phoenix Tuner.",
			"Move the mechanism off the limit.",
			{ kind: "check", text: "Still blocked in that direction?", yes: "Continue.", no: "Problem solved." },
			"Have the team clear the soft limit or fix the remote sensor in code.",
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.in-boot-loader": {
		device: "Victor SPX",
		led: "Status",
		state: "One LED alternates green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: [
			"Field-upgrade the firmware in Phoenix Tuner.",
			{ kind: "check", text: "Does it refuse the firmware?", yes: "Swap the device.", no: "Problem solved." },
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.normal-operation-codes.neutral-signal-applied-within-deadband": {
		device: "Victor SPX",
		led: "Status",
		state: "Both solid orange",
		meaning: "Enabled with zero output, or the command is inside the deadband. Normal.",
		steps: [
			{ kind: "check", text: "Should it be moving?", yes: "Continue.", no: "Problem solved." },
			"Check the joystick and the code for a zero command.",
		],
		source: CTRE_VSPX,
	},
	"ctrevictorspx.b-c-cal-button-color-codes.brake-mode": {
		device: "Victor SPX",
		led: "B/C CAL button",
		state: "Solid red",
		meaning: "Brake mode. The motor shorts its leads when the output is neutral.",
		source: CTRE_VSPX,
	},
	"ctrevictorspx.b-c-cal-button-color-codes.coast-mode": {
		device: "Victor SPX",
		led: "B/C CAL button",
		state: "Off",
		meaning: "Coast mode. The motor spins freely when the output is neutral.",
		source: CTRE_VSPX,
	},
	"ctrecanivore.stat.powered-but-usb-not-plugged-in": {
		device: "CANivore",
		led: "STAT",
		state: "Red double blink",
		meaning: "12 V is present on V+ and V- but there is no USB connection.",
		steps: [
			"Plug the USB cable into the roboRIO.",
			"Confirm the roboRIO is powered.",
			{ kind: "check", text: "Still a red double blink?", yes: "Swap the USB cable.", no: "Problem solved." },
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.usb-plugged-in-but-no-comms": {
		device: "CANivore",
		led: "STAT",
		state: "Red fast strobe",
		meaning:
			"USB is connected but there is no USB communication. The roboRIO is still booting, or the cable or port is bad.",
		steps: [
			"Wait for the roboRIO to finish booting.",
			"Swap the USB cable.",
			"Try the other roboRIO USB port.",
			{ kind: "check", text: "Does Phoenix Tuner X see the CANivore now?", yes: "Problem solved.", no: "Swap the CANivore." },
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.can-disabled-no-power": {
		device: "CANivore",
		led: "STAT",
		state: "Orange double blink",
		meaning:
			"USB is good but CAN streaming is disabled, and V+ and V- are not powered. No Phoenix program is running.",
		steps: [...PHOENIX_NOT_RUNNING_STEPS.slice(0, 2), "Wire V+ and V- to 12 V for use on a robot."],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.can-disabled": {
		device: "CANivore",
		led: "STAT",
		state: "Orange fast strobe",
		meaning: "USB is good but CAN streaming is disabled. No Phoenix program is running.",
		steps: PHOENIX_NOT_RUNNING_STEPS.slice(0, 2),
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.can-enabled-no-power": {
		device: "CANivore",
		led: "STAT",
		state: "Green double blink",
		meaning: "USB is good and CAN streaming is enabled. V+ and V- are not powered.",
		steps: ["Normal on a bench over USB.", "On a robot, wire V+ and V- to 12 V."],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.can-enabled": {
		device: "CANivore",
		led: "STAT",
		state: "Green fast strobe",
		meaning: "USB is good, CAN streaming is enabled, and V+ and V- are powered. Normal.",
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.bootloader": {
		device: "CANivore",
		led: "STAT",
		state: "Alternating green and orange",
		meaning: "The CANivore is in its bootloader with no application firmware.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.stat.hardware-damage": {
		device: "CANivore",
		led: "STAT",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.wi-fi.wi-fi-enabled": {
		device: "CANivore",
		led: "Wi-Fi",
		state: "Blinking green",
		meaning: "The CANivore's Wi-Fi is on, for wireless Phoenix Tuner X.",
		steps: [
			"Turn Wi-Fi off before the robot goes to the field. Robot wireless devices other than the radio are not allowed.",
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.wi-fi.wi-fi-disabled": {
		device: "CANivore",
		led: "Wi-Fi",
		state: "Off",
		meaning: "Wi-Fi is off. This is the state you want on the field.",
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.bluetooth.bluetooth-enabled": {
		device: "CANivore",
		led: "Bluetooth",
		state: "Blinking green",
		meaning: "Bluetooth is on.",
		steps: [
			"Turn Bluetooth off before the robot goes to the field. Robot wireless devices other than the radio are not allowed.",
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.bluetooth.bluetooth-disabled": {
		device: "CANivore",
		led: "Bluetooth",
		state: "Off",
		meaning: "Bluetooth is off. This is the state you want on the field.",
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.no-power": {
		device: "CANivore",
		led: "CAN",
		state: "Off",
		meaning: "No power. No 5 V from USB and no 12 V on V+ and V-.",
		steps: ["Plug in USB or wire V+ and V- to 12 V."],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.voltage-too-low-for-can-bus": {
		device: "CANivore",
		led: "CAN",
		state: "Solid red",
		meaning: "Supply voltage is too low to run the CAN transceiver.",
		steps: [
			"Confirm 5 V over USB, and 12 V on V+ and V- if wired.",
			"Swap the USB cable.",
			"Check the V+ and V- crimps.",
			{ kind: "check", text: "Is the CAN LED still solid red?", yes: "Swap the CANivore.", no: "Problem solved." },
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.no-can-comms-termination-enabled": {
		device: "CANivore",
		led: "CAN",
		state: "Red fast strobe",
		meaning: "No CAN communication. The CANivore's own termination is on.",
		steps: [
			"Check CANH and CANL (yellow, green) at the CANivore and the first device.",
			"Confirm every device on this bus supports CAN FD.",
			"Confirm the far end of the bus has a 120 ohm terminator.",
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.no-can-comms-termination-disabled": {
		device: "CANivore",
		led: "CAN",
		state: "Red double blink",
		meaning: "No CAN communication. The CANivore's own termination is off.",
		steps: [
			"Check CANH and CANL (yellow, green) at the CANivore and the first device.",
			"Confirm every device on this bus supports CAN FD.",
			"The bus needs two 120 ohm terminators, one at each end. Turn the CANivore's termination on if it is at the end.",
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.can-2-0b-legacy-mode-termination-enabled": {
		device: "CANivore",
		led: "CAN",
		state: "Orange fast strobe",
		meaning: "The bus is running as CAN 2.0B, not CAN FD. A device on this bus does not support CAN FD.",
		steps: [
			{ kind: "check", text: "Is legacy CAN 2.0B mode intended here?", yes: "Nothing to do.", no: "Continue." },
			"Find the non-FD device (Talon SRX, Victor SPX, older) and move it to the roboRIO bus.",
		],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.can-2-0b-legacy-mode-termination-disabled": {
		device: "CANivore",
		led: "CAN",
		state: "Orange double blink",
		meaning: "The bus is running as CAN 2.0B, not CAN FD, and the CANivore's termination is off.",
		steps: ["Find the non-FD device and move it to the roboRIO bus.", "Check the bus has two 120 ohm terminators."],
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.can-fd-active-termination-enabled": {
		device: "CANivore",
		led: "CAN",
		state: "Green fast strobe",
		meaning: "CAN FD is active and the CANivore is terminating. Normal.",
		source: CTRE_CANIVORE,
	},
	"ctrecanivore.can.can-fd-active-termination-disabled": {
		device: "CANivore",
		led: "CAN",
		state: "Green double blink",
		meaning: "CAN FD is active. The CANivore's termination is off, so something else must terminate that end.",
		steps: [
			{ kind: "check", text: "Do devices drop off this bus?", yes: "Continue.", no: "Problem solved." },
			"Check both ends of the bus have a 120 ohm terminator.",
		],
		source: CTRE_CANIVORE,
	},
	"ctrepigeon.no-power": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "Both off",
		meaning: "No 12 V on the red and black leads.",
		steps: [
			"Check the power source and breaker.",
			"Check the crimps at both ends.",
			{ kind: "check", text: "Is the LED still off?", yes: "Swap the device.", no: "Problem solved." },
		],
		source: CTRE_PIGEON,
	},
	"ctrepigeon.invalid-can-signal": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "Alternating red",
		meaning: "No valid CAN connection.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_PIGEON,
	},
	"ctrepigeon.valid-can-phoenix-is-not-detected": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "Alternating orange",
		meaning: "CAN is fine but no Phoenix based robot program is talking to it.",
		steps: PHOENIX_NOT_RUNNING_STEPS,
		source: CTRE_PIGEON,
	},
	"ctrepigeon.valid-can-phoenix-detected-robot-disabled": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "Both blink orange together",
		meaning: "CAN and Phoenix detected, robot disabled. Normal.",
		source: CTRE_PIGEON,
	},
	"ctrepigeon.valid-can-phoenix-detected-robot-enabled": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "Alternating green",
		meaning: "CAN and Phoenix detected, robot enabled. Normal.",
		steps: [
			{ kind: "check", text: "Does the heading drift?", yes: "Continue.", no: "Problem solved." },
			"Run mount calibration in Phoenix Tuner X with the robot held still.",
		],
		source: CTRE_PIGEON,
	},
	"ctrepigeon.hardware-fault-detected-confirm-with-tunerx-self-test": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_PIGEON,
	},
	"ctrepigeon.device-in-bootloader-field-upgrade-device-in-tunerx": {
		device: "Pigeon 2.0",
		led: "Status",
		state: "One LED alternates green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_PIGEON,
	},
	"ctrecancoder.no-power": {
		device: "CANcoder",
		led: "Status",
		state: "Off",
		meaning: "No 12 V on the red and black leads.",
		steps: [
			"Check the power source and breaker.",
			"Check the crimps at both ends.",
			{ kind: "check", text: "Is the LED still off?", yes: "Swap the device.", no: "Problem solved." },
		],
		source: CTRE_CANCODER,
	},
	"ctrecancoder.bootloader": {
		device: "CANcoder",
		led: "Status",
		state: "Alternating green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_CANCODER,
	},
	"ctrecancoder.unlicensed-phoenix-pro": {
		device: "CANcoder",
		led: "Status",
		state: "Alternating red and green",
		meaning: "Code used a Phoenix Pro only feature on an unlicensed device.",
		steps: ["License the device in Phoenix Tuner X, or change the code to non-Pro features."],
		source: CTRE_CANCODER,
	},
	"ctrecancoder.can-bus-has-been-lost": {
		device: "CANcoder",
		led: "Status",
		state: "Slow bright red blink",
		meaning: "The CANcoder had CAN and lost it.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_CANCODER,
	},
	"ctrecancoder.dim-no-can-and-magnet-out-of-range": {
		device: "CANcoder",
		led: "Status",
		state: "Rapid dim red",
		meaning: "No CAN since boot, and the magnet is out of range (too far, too close, or missing).",
		steps: [
			"Fix CAN first: check CANH and CANL wiring and that the roboRIO is on.",
			"Check the magnet is present, centered on the sensor axis, and at the distance in the CANcoder user guide.",
		],
		source: CTRE_CANCODER,
	},
	"ctrecancoder.dim-no-can-and-reduced-magnet-accuracy": {
		device: "CANcoder",
		led: "Status",
		state: "Rapid dim orange",
		meaning: "No CAN since boot. The magnet is in range but with reduced accuracy.",
		steps: [
			"Fix CAN first: check CANH and CANL wiring and that the roboRIO is on.",
			"Adjust the magnet distance and centering until the LED is green.",
		],
		source: CTRE_CANCODER,
	},
	"ctrecancoder.dim-no-can-and-magnet-present": {
		device: "CANcoder",
		led: "Status",
		state: "Rapid dim green",
		meaning: "No CAN since boot. The magnet is good.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_CANCODER,
	},
	"ctrecancoder.bright-can-and-magnet-out-of-range": {
		device: "CANcoder",
		led: "Status",
		state: "Rapid bright red",
		meaning:
			"CAN is good. The magnet is out of range (too far, too close, or missing). Position readings are not valid.",
		steps: [
			"Check the magnet is present and has not fallen out of the shaft.",
			"Center the magnet on the sensor axis and set the distance per the CANcoder user guide.",
			{ kind: "check", text: "Still rapid bright red with a good magnet fitted?", yes: "Swap the CANcoder.", no: "Problem solved." },
		],
		source: CTRE_CANCODER,
	},
	"ctrecancoder.bright-can-and-reduced-magnet-accuracy": {
		device: "CANcoder",
		led: "Status",
		state: "Rapid bright orange",
		meaning: "CAN is good. The magnet is in range but with reduced accuracy.",
		steps: [
			"Adjust the magnet distance and centering until the LED is green.",
			"Usable in a pinch. Fix it before the next match.",
		],
		source: CTRE_CANCODER,
	},
	"ctrecancoder.bright-can-and-magnet-present": {
		device: "CANcoder",
		led: "Status",
		state: "Rapid bright green",
		meaning: "CAN is good and the magnet is in range. Normal.",
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.no-power": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Off",
		meaning: "No 12 V on the red and black leads.",
		steps: [
			"Check the power source and breaker.",
			"Check the crimps at both ends.",
			{ kind: "check", text: "Is the LED still off?", yes: "Swap the device.", no: "Problem solved." },
		],
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.bootloader": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Alternating green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.unlicensed-phoenix-pro": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Alternating red and green",
		meaning: "Code used a Phoenix Pro only feature on an unlicensed device.",
		steps: ["License the device in Phoenix Tuner X, or change the code to non-Pro features."],
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.can-bus-has-been-lost": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Slow bright red blink",
		meaning: "The CANcoder had CAN and lost it.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.dim-no-can-and-magnet-out-of-range": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Rapid dim red",
		meaning: "No CAN since boot, and the magnet is out of range.",
		steps: [
			"Fix CAN first: check CANH and CANL wiring and that the roboRIO is on.",
			"Check the magnet ring is seated on the shaft and centered in the bore.",
		],
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.dim-no-can-and-reduced-magnet-accuracy": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Rapid dim orange",
		meaning: "No CAN since boot. The magnet is in range but with reduced accuracy.",
		steps: [
			"Fix CAN first: check CANH and CANL wiring and that the roboRIO is on.",
			"Adjust the magnet seating until the LED is green.",
		],
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.dim-no-can-and-magnet-present": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Rapid dim green",
		meaning: "No CAN since boot. The magnet is good.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.bright-can-and-magnet-out-of-range": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Rapid bright red",
		meaning: "CAN is good. The magnet is out of range. Position readings are not valid.",
		steps: [
			"Check the magnet ring is on the shaft and has not slipped.",
			"Center it in the bore and set the distance per the user guide.",
			{ kind: "check", text: "Still rapid bright red with the ring seated right?", yes: "Swap the CANcoder.", no: "Problem solved." },
		],
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.bright-can-and-reduced-magnet-accuracy": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Rapid bright orange",
		meaning: "CAN is good. The magnet is in range but with reduced accuracy.",
		steps: [
			"Adjust the magnet seating until the LED is green.",
			"Usable in a pinch. Fix it before the next match.",
		],
		source: CTRE_CANCODER,
	},
	"ctretbcancoder.bright-can-and-magnet-present": {
		device: "Throughbore CANcoder",
		led: "Status",
		state: "Rapid bright green",
		meaning: "CAN is good and the magnet is in range. Normal.",
		source: CTRE_CANCODER,
	},
	"ctrecanrange.no-power": {
		device: "CANrange",
		led: "Status",
		state: "Off",
		meaning: "No 12 V on V+ and V-.",
		steps: [
			"Check the power source and breaker.",
			"Check the crimps at both ends.",
			{ kind: "check", text: "Is the LED still off?", yes: "Swap the device.", no: "Problem solved." },
		],
		source: CTRE_CANRANGE,
	},
	"ctrecanrange.bootloader": {
		device: "CANrange",
		led: "Status",
		state: "One LED alternates green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_CANRANGE,
	},
	"ctrecanrange.can-bus-has-been-lost": {
		device: "CANrange",
		led: "Status",
		state: "Blinking red",
		meaning: "No valid CAN.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_CANRANGE,
	},
	"ctrecanrange.can-present-distance-not-detected": {
		device: "CANrange",
		led: "Status",
		state: "Blinking orange",
		meaning: "CAN is good. Nothing is inside the detection threshold.",
		steps: [
			{ kind: "check", text: "Should it be detecting a target now?", yes: "Continue.", no: "Problem solved." },
			"Check the sensor has clear line of sight and the target is inside the threshold set in Phoenix Tuner X.",
			"Wipe the lens.",
		],
		source: CTRE_CANRANGE,
	},
	"ctrecanrange.can-present-distance-detected-any-speed": {
		device: "CANrange",
		led: "Status",
		state: "Blinking green",
		meaning: "CAN is good and something is inside the detection threshold. Faster blink means closer.",
		source: CTRE_CANRANGE,
	},
	"ctrecanrange.damaged-hardware": {
		device: "CANrange",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_CANRANGE,
	},
	"ctrecandle.no-power-or-statusledwhenactive-config-is-set-to-disabled": {
		device: "CANdle",
		led: "Status",
		state: "Off",
		meaning:
			"No power, or the StatusLedWhenActive config is set to Disabled, which turns the status LED off while the device is controlled.",
		steps: [
			{ kind: "check", text: "Is the strip lit with code running?", yes: "Nothing to do.", no: "Continue." },
			"Check 12 V on the +Vin and -Vin leads and the breaker or fuse.",
		],
		source: CTRE_CANDLE,
	},
	"ctrecandle.can-present-not-being-controlled": {
		device: "CANdle",
		led: "Status",
		state: "Blinking orange",
		meaning: "CAN is good but no robot program is sending it commands.",
		steps: PHOENIX_NOT_RUNNING_STEPS,
		source: CTRE_CANDLE,
	},
	"ctrecandle.can-present-actively-being-controlled": {
		device: "CANdle",
		led: "Status",
		state: "Blinking green",
		meaning: "CAN is good and the robot program is controlling it. Normal.",
		steps: [
			{ kind: "check", text: "Is the LED strip dark anyway?", yes: "Continue.", no: "Problem solved." },
			"Check the strip wiring and the 5 V or 12 V output selection.",
		],
		source: CTRE_CANDLE,
	},
	"ctrecandle.bootloader": {
		device: "CANdle",
		led: "Status",
		state: "Alternating green and orange",
		meaning: "The device is in its bootloader with no application firmware.",
		steps: CTRE_BOOTLOADER_STEPS,
		source: CTRE_CANDLE,
	},
	"ctrecandle.no-can-detected": {
		device: "CANdle",
		led: "Status",
		state: "Blinking red",
		meaning: "No valid CAN, and no pixel pulse train.",
		steps: CAN_WIRING_STEPS,
		source: CTRE_CANDLE,
	},
	"ctrecandle.5v-too-high-fault": {
		device: "CANdle",
		led: "Status",
		state: "Rapid red",
		meaning: "The 5 V output is too high.",
		steps: [
			"Check for a short between +Vout and the 5 V output.",
			"Unplug the LED strip and power cycle.",
			{ kind: "check", text: "Does the 5 V fault stay with the strip unplugged?", yes: "Swap the CANdle.", no: "Problem solved." },
		],
		source: CTRE_CANDLE,
	},
	"ctrecandle.short-circuit-or-software-fuse-fault": {
		device: "CANdle",
		led: "Status",
		state: "Red blip",
		meaning: "Short circuit on the output, or the strip draws more than the 6 A software fuse allows.",
		steps: [
			"Unplug the LED strip.",
			{ kind: "check", text: "Does the fault clear with the strip unplugged?", yes: "Replace the strip or its cable.", no: "Continue." },
			"Reduce the LED count or the brightness. The strip limit is 6 A.",
			"Read the fault in Phoenix Tuner X.",
			"Power cycle the CANdle.",
		],
		source: CTRE_CANDLE,
	},
	"ctrecandle.thermal-fault": {
		device: "CANdle",
		led: "Status",
		state: "Orange blip",
		meaning: "The CANdle is too hot.",
		steps: [
			"Let it cool.",
			"Lower the brightness or LED count, or disable the onboard LEDs.",
			"Mount it where air can move.",
		],
		source: CTRE_CANDLE,
	},
	"ctrecandle.damaged-hardware": {
		device: "CANdle",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The device detected hardware damage.",
		steps: CTRE_DAMAGED_STEPS,
		source: CTRE_CANDLE,
	},
	"ctrepowerdistributionpanel.no-power": {
		device: "Power Distribution Panel",
		led: "STAT / COMM",
		state: "Off",
		meaning: "No power to the PDP logic, or the battery is connected backwards.",
		steps: [
			"Check the main breaker is on and the battery is connected.",
			"Check battery polarity at the PDP.",
			"Check the main battery lugs are tight.",
			{ kind: "check", text: "Is the LED still off with the battery connected right?", yes: "Swap the PDP.", no: "Problem solved." },
		],
		source: CTRE_PDP,
	},
	"ctrepowerdistributionpanel.robot-enabled": {
		device: "Power Distribution Panel",
		led: "STAT / COMM",
		state: "Green fast blink",
		meaning: "CAN is good, no fault, robot enabled. Normal.",
		source: CTRE_PDP,
	},
	"ctrepowerdistributionpanel.robot-disabled": {
		device: "Power Distribution Panel",
		led: "STAT / COMM",
		state: "Green slow blink",
		meaning: "CAN is good, no fault, robot disabled. Normal.",
		source: CTRE_PDP,
	},
	"ctrepowerdistributionpanel.disabled-sticky-fault-present": {
		device: "Power Distribution Panel",
		led: "STAT / COMM",
		state: "Orange slow blink",
		meaning: "A sticky fault was recorded earlier, such as a brownout. It does not block anything.",
		steps: [
			"Read the fault in the DS or Phoenix Tuner.",
			"Clear the sticky faults from code or Tuner.",
			{ kind: "check", text: "Is the logged fault a brownout?", yes: "Check the battery.", no: "Problem solved." },
		],
		source: CTRE_PDP,
	},
	"ctrepowerdistributionpanel.no-can": {
		device: "Power Distribution Panel",
		led: "STAT / COMM",
		state: "Red slow blink",
		meaning: "No CAN communication with the roboRIO. The PDP still delivers power; only current logging is lost.",
		steps: [
			"Check the CAN wires at the PDP.",
			"Check the termination jumper on the PDP. It must be on if the PDP is the end of the bus.",
			"Confirm robot code is running.",
		],
		source: CTRE_PDP,
	},
	"ctrepowerdistributionpanel.comm-only-in-boot-loader-field-upgrade-necessary": {
		device: "Power Distribution Panel",
		led: "COMM",
		state: "Alternating green and orange",
		meaning: "The PDP is in its bootloader. Power still flows, but it needs firmware.",
		steps: [
			"Field-upgrade the firmware in Phoenix Tuner.",
			{ kind: "check", text: "Does it refuse the firmware?", yes: "Continue.", no: "Problem solved." },
			"The PDP still powers the robot. Swap it when you can.",
		],
		source: CTRE_PDP,
	},
	"ctrepowerdistributionpanel.hardware-damaged-do-not-attempt-to-use": {
		device: "Power Distribution Panel",
		led: "STAT / COMM",
		state: "Alternating red and orange",
		meaning: "The PDP detected hardware damage. CTRE says do not use it.",
		steps: ["Swap the PDP.", "Check battery polarity and look for metal debris before powering the replacement."],
		source: CTRE_PDP,
	},
	"ctrepneumaticscontrolmodule.status.no-power": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Off",
		meaning: "No power, or the power leads are reversed. The Status LED should always be lit.",
		steps: [
			"Check the Vin leads to the PDP and their polarity.",
			"Check the breaker or fuse on that channel.",
			"Check for broken wires.",
			{ kind: "check", text: "Is the Status LED still off?", yes: "Swap the PCM.", no: "Problem solved." },
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.robot-enabled": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Green fast blink",
		meaning: "CAN is good, no fault, robot enabled. Solenoids and compressor are live.",
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.robot-disabled": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Green slow blink",
		meaning: "CAN is good, no fault, robot disabled. Normal.",
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.disabled-sticky-fault-present": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Orange slow blink",
		meaning:
			"A solenoid or compressor fault happened earlier and has not been cleared. Sticky faults survive power cycles.",
		steps: [
			"Read the most recent fault in the DS or Phoenix Tuner.",
			"Fix the cause (see the solenoid or compressor fault rows).",
			"Clear the sticky fault from code or Tuner.",
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.no-can-or-solenoid-fault-will-blink-of-faulted-solenoid-followed-by-pause": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Red blinks",
		meaning:
			"Red strobe with no pattern: no CAN communication. Red blinks counted then a pause: that solenoid channel is faulted (shorted or damaged solenoid).",
		steps: [
			"A red strobe with no pattern means no CAN. Check the CAN wires, termination, and that the roboRIO is on.",
			"Counted blinks with a pause point to one solenoid channel. Count them to find it.",
			"Unplug that solenoid and check its wiring for a short.",
			"Remove any metal debris at the solenoid terminals.",
			"Power cycle the PCM.",
			"Clear the sticky fault from code or Tuner.",
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.compressor-fault": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Red long blink every 2 s",
		meaning: "Compressor current too high. The PCM retries the compressor every 5 seconds.",
		steps: [
			"Check for a short across the compressor terminals and along the compressor wiring.",
			"Check the compressor turns freely.",
			"Remove any metal debris.",
			"Power cycle the PCM.",
			"Clear the sticky fault from code or Tuner.",
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.in-boot-loader-field-upgrade-necessary": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Alternating green and orange",
		meaning: "The PCM is in its bootloader with no application firmware. Solenoids and compressor will not run.",
		steps: [
			"Field-upgrade the firmware in Phoenix Tuner.",
			{ kind: "check", text: "Does it refuse the firmware?", yes: "Swap the PCM.", no: "Problem solved." },
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.status.hardware-damaged-do-not-attempt-to-use": {
		device: "Pneumatics Control Module",
		led: "Status",
		state: "Alternating red and orange",
		meaning: "The PCM detected hardware damage. CTRE says do not use it.",
		steps: ["Swap the PCM.", "Check power polarity and solenoid wiring before powering the replacement."],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.compressor-led-comp.compressor-off": {
		device: "Pneumatics Control Module",
		led: "COMP",
		state: "Off",
		meaning: "The compressor output is off.",
		steps: [
			{ kind: "check", text: "Should the compressor be running now?", yes: "Continue.", no: "Problem solved." },
			"Confirm the robot is enabled, the code creates a pneumatics object, and the pressure switch is wired and open.",
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.compressor-led-comp.compressor-on": {
		device: "Pneumatics Control Module",
		led: "COMP",
		state: "Green solid",
		meaning: "The compressor output is on.",
		steps: [
			{ kind: "check", text: "Is the compressor silent with this LED on?", yes: "Continue.", no: "Problem solved." },
			"Check the compressor wiring and the compressor itself.",
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.solenoid-status-led.solenoid-off": {
		device: "Pneumatics Control Module",
		led: "Solenoid",
		state: "Off",
		meaning: "That solenoid channel is not energized.",
		steps: [
			{ kind: "check", text: "Should this solenoid be energized now?", yes: "Continue.", no: "Problem solved." },
			"Check the code and the channel number.",
		],
		source: CTRE_PCM,
	},
	"ctrepneumaticscontrolmodule.solenoid-status-led.solenoid-on": {
		device: "Pneumatics Control Module",
		led: "Solenoid",
		state: "Red solid",
		meaning: "That solenoid channel is energized.",
		steps: [
			{ kind: "check", text: "Does the cylinder stay put with this LED on?", yes: "Continue.", no: "Problem solved." },
			"Check air pressure, the solenoid wiring, and the PCM voltage jumper (12 V or 24 V).",
		],
		source: CTRE_PCM,
	},
} as const satisfies Record<string, StatusLightHelp>;
