// Status light help: roboRIO, SystemCore and Vivid radio. See shared.ts for the step rules.

import { type StatusLightHelp, NI_FLASHING, NI_RED, SC_OS, SC_SPEC, VIVID, VIVID_BOOTLOOP, WPILIB, WPILIB_BROWNOUT, WPILIB_IMAGING } from "./shared";

// roboRIO reimaging differs by model, so each line is one action inline here.
const REIMAGE_RIO = [
	"On a roboRIO 1, reimage over USB with the roboRIO Imaging Tool (Format Target).",
	"On a roboRIO 2, reimage the microSD card on a laptop with balenaEtcher or Raspberry Pi Imager.",
	"On a roboRIO 2, put the card back and set the team number over USB with the Imaging Tool.",
] as const;

export const generalHelp = {
	"radio.no-power": {
		device: "VH-109 radio",
		led: "All LEDs",
		state: "Off",
		meaning: "The radio has no power. PWR is the first LED to light when power is present.",
		steps: [
			"Check the power lead at the radio and at its source: PDP or PDH channel, or PoE injector.",
			{ kind: "check", text: "PWR still off?", yes: "Continue.", no: "Problem solved." },
			"Check the breaker or fuse on that channel.",
			{ kind: "check", text: "PWR still off?", yes: "Continue.", no: "Problem solved." },
			"Swap the power cable. Crimps on radio leads fail often.",
			{ kind: "check", text: "PWR still off with known good 12 V at the radio?", yes: "Swap the radio.", no: "Problem solved." },
		],
		source: VIVID,
	},
	"radio.powered-booting": {
		device: "VH-109 radio",
		led: "PWR / SYS",
		state: "PWR solid, SYS off",
		meaning: "The radio has power and is booting. SYS stays off until boot completes.",
		steps: [
			"Wait for SYS to light. It stays off until boot completes.",
			{ kind: "check", text: "SYS still off?", yes: "Continue.", no: "Problem solved." },
			"Power cycle the radio once.",
			{ kind: "check", text: "Does the radio reboot in a loop, or never boot?", yes: "Continue.", no: "Problem solved." },
			"Swap the radio. A bootloop means corrupt flash memory (Vivid known issue 1); recovery needs Vivid support through WCP.",
		],
		source: VIVID_BOOTLOOP,
	},
	"radio.powered-unable-to-ping-field": {
		device: "VH-109 radio",
		led: "SYS",
		state: "Blinking 1 Hz",
		meaning:
			"The radio booted but cannot reach the field access point (10.TE.AM.4). The robot is not on the field network, or the radio is not programmed for this event.",
		steps: [
			"Confirm the radio was programmed at this event's kiosk with the correct team number.",
			"Confirm the team is in the current match. The field access point only accepts the six scheduled teams.",
			"Look at the 6G LED. No 6 GHz link means the wireless association failed.",
			"Power cycle the radio.",
			{ kind: "check", text: "SYS still blinking 1 Hz?", yes: "Continue.", no: "Problem solved." },
			"Reprogram the radio at the kiosk.",
			{
				kind: "check",
				text: "SYS still blinking 1 Hz while other robots reach the field?",
				yes: "Swap the radio.",
				no: "Problem solved.",
			},
		],
		source: VIVID,
	},
	"radio.powered-flashing-firmware": {
		device: "VH-109 radio",
		led: "SYS",
		state: "Blinking 20 Hz",
		meaning: "Firmware is being written to the radio. This happens during a kiosk flash.",
		steps: [
			"Do not remove power. Wait for the flash to finish.",
			"Watch for SYS to change to a 50 Hz blink, then a reboot. That means the flash worked.",
			{ kind: "check", text: "SYS still blinking 20 Hz after several minutes?", yes: "Continue.", no: "Problem solved." },
			"Power cycle the radio.",
			{ kind: "check", text: "SYS still blinking 20 Hz?", yes: "Flash it again at the kiosk.", no: "Problem solved." },
		],
		source: VIVID,
	},
	"radio.powered-firmware-flashed-in-first-boot": {
		device: "VH-109 radio",
		led: "SYS",
		state: "Blinking 50 Hz",
		meaning: "The firmware flash succeeded and the radio is running its first-boot setup.",
		steps: [
			"Wait. Do not remove power until SYS is solid or blinking at 1 Hz.",
			{ kind: "check", text: "SYS still not solid or blinking 1 Hz after a minute?", yes: "Continue.", no: "Problem solved." },
			"Power cycle once.",
			{ kind: "check", text: "SYS still not solid or blinking 1 Hz?", yes: "Reflash at the kiosk.", no: "Problem solved." },
		],
		source: VIVID,
	},
	"radio.radio-in-ap-mode-with-battery-detected": {
		device: "VH-109 radio",
		led: "SYS / 2.4G / 6G",
		state: "All blinking 20 Hz together",
		meaning:
			"The radio is programmed as an access point (home practice setup) but it is powered from a robot battery. Wireless is disabled until this is fixed.",
		steps: [
			"Reprogram the radio at the event kiosk as a robot radio.",
			"Power cycle the radio. The lockout only clears on a power cycle.",
			{
				kind: "check",
				text: "All LEDs still blinking 20 Hz together?",
				yes: "Reprogram again as a robot radio.",
				no: "Problem solved.",
			},
			"For home practice, run the access point on a spare radio and a bench supply, never the robot battery.",
		],
		source: VIVID,
	},
	"radio.powered-able-to-ping-field": {
		device: "VH-109 radio",
		led: "SYS",
		state: "Solid",
		meaning: "Normal. The radio is linked to the field and can reach the field access point.",
		steps: [
			{
				kind: "check",
				text: "Driver Station still shows no robot?",
				yes: "Check the RIO LED and the roboRIO Comm LED.",
				no: "Problem solved.",
			},
		],
		source: VIVID,
	},
	"radio.no-robot-radio-link": {
		device: "VH-109 radio",
		led: "2.4G / 6G / RIO",
		state: "Off",
		meaning:
			"Neither wireless band shows a link and the RIO port has no Ethernet link. The radio is up but nothing is connected through it.",
		steps: [
			"Reseat both ends of the Ethernet cable from the roboRIO to the radio's RIO port.",
			{ kind: "check", text: "RIO LED still off?", yes: "Continue.", no: "Problem solved." },
			"Swap the Ethernet cable.",
			{ kind: "check", text: "RIO LED still off?", yes: "Continue.", no: "Problem solved." },
			"Confirm the roboRIO is powered and booted. Its Status LED goes off when boot completes.",
			"Reprogram the radio at the kiosk. No 6 GHz link means it is not associating.",
			"Power cycle the radio.",
			{
				kind: "check",
				text: "RIO LED still off with a known good cable and roboRIO?",
				yes: "Swap the radio.",
				no: "Problem solved.",
			},
		],
		source: VIVID,
	},
	"radio.2-4ghz-connection-enabled": {
		device: "VH-109 radio",
		led: "2.4G",
		state: "Solid",
		meaning:
			"The 2.4 GHz radio is active. The field uses 6 GHz for the robot link. 2.4 GHz is for a robot hosted practice network.",
		steps: [
			{
				kind: "check",
				text: "Driver Station has no comms?",
				yes: "Check the 6G LED and the SYS LED first.",
				no: "Problem solved.",
			},
			{
				kind: "check",
				text: "Is 2.4G on when the team did not expect it?",
				yes: "Reprogram the radio at the kiosk.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"radio.6ghz-connection-enabled": {
		device: "VH-109 radio",
		led: "6G",
		state: "Solid",
		meaning: "The 6 GHz link to the field access point is up. This is the normal field link.",
		steps: [
			{
				kind: "check",
				text: "Driver Station has no comms with 6G lit?",
				yes: "Check the RIO LED and the roboRIO Comm LED.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"radio.valid-rio-connection": {
		device: "VH-109 radio",
		led: "RIO",
		state: "Solid",
		meaning: "Ethernet link on the RIO port. The cable to the roboRIO is connected and the roboRIO port is up.",
		steps: [
			{ kind: "check", text: "Driver Station still has no comms?", yes: "Continue.", no: "Problem solved." },
			"Look at the roboRIO Comm LED. Off means the roboRIO is not seeing the Driver Station.",
			{
				kind: "check",
				text: "Comm LED off?",
				yes: "Check the team number on the roboRIO and the DS.",
				no: "Problem solved.",
			},
		],
		source: VIVID,
	},
	"roborio.power.ok": {
		device: "roboRIO",
		led: "Power",
		state: "Solid green",
		meaning: "Input power is good and no rail fault is active.",
		steps: [
			{
				kind: "check",
				text: "Robot has no comms?",
				yes: "Check the Status LED and the Comm LED.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.power.brownout": {
		device: "roboRIO",
		led: "Power",
		state: "Solid amber",
		meaning:
			"Battery voltage dropped below 6.3 V. The roboRIO disabled all outputs and the user rails until voltage recovers above 7.5 V. The Driver Station shows Voltage Brownout.",
		steps: [
			"Swap to a fresh, fully charged battery.",
			{ kind: "check", text: "Power LED still amber?", yes: "Continue.", no: "Problem solved." },
			"Check the main battery connections and the main breaker for heat, corrosion, or loose lugs.",
			{ kind: "check", text: "Power LED still amber?", yes: "Continue.", no: "Problem solved." },
			"Look for a stalled motor or a short pulling high current. The DS log and PDP or PDH channel currents show it.",
			{
				kind: "check",
				text: "Does it brown out again on a good battery?",
				yes: "Add current limits in code or cut simultaneous load.",
				no: "Problem solved.",
			},
		],
		source: WPILIB_BROWNOUT,
	},
	"roborio.power.fault-short": {
		device: "roboRIO",
		led: "Power",
		state: "Solid red",
		meaning:
			"One of the user voltage rails (3.3 V, 5 V, 6 V) is shorted or overloaded. Metal shavings inside the case are the usual cause.",
		steps: [
			"In the Driver Station, click the power (lightning) indicator. It names the faulted rail.",
			"Unplug everything from DIO, PWM, analog, I2C, SPI, MXP and USB.",
			{
				kind: "check",
				text: "Power LED still red with everything unplugged?",
				yes: "Continue.",
				no: "Plug devices back one at a time to find the short.",
			},
			"Open the case: 4 screws on the back, 2 at the power port. Blow it out with compressed air and look for metal shavings.",
			{
				kind: "check",
				text: "Power LED still red with nothing connected and a clean board?",
				yes: "Swap the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: NI_RED,
	},
	"roborio.power.input-too-high": {
		device: "roboRIO",
		led: "Power",
		state: "Flashing red",
		meaning: "Input voltage is above 16 V. All outputs are disabled, including the RSL.",
		steps: [
			"Check what powers the roboRIO. It must be the dedicated roboRIO output of the PDP or PDH, from a 12 V FRC battery.",
			"Measure the battery. An overcharged or wrong battery reads high.",
			"Fix the supply.",
			"Power cycle the roboRIO.",
			{
				kind: "check",
				text: "Power LED still flashing red on a good 12 V supply?",
				yes: "Swap the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: NI_RED,
	},
	"roborio.status.ok": {
		device: "roboRIO",
		led: "Status",
		state: "Off",
		meaning: "Off is normal. The Status LED only lights during boot and for error codes.",
		steps: [
			{
				kind: "check",
				text: "Robot has no comms?",
				yes: "Check the Comm LED and the radio.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.status.booting": {
		device: "roboRIO",
		led: "Status",
		state: "Solid while booting",
		meaning: "Power-on self test. The LED turns off when boot completes.",
		steps: [
			"Wait for it to turn off. It clears when boot completes.",
			{
				kind: "check",
				text: "Status LED still solid long after power-on with no comms?",
				yes: "Treat it as the unrecoverable error.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.status.2-blinks": {
		device: "roboRIO",
		led: "Status",
		state: "2 blinks, pause",
		meaning: "Software error. Usually an image or firmware update that was interrupted.",
		steps: [
			"Power cycle once.",
			{ kind: "check", text: "Status LED still blinking 2 times?", yes: "Continue.", no: "Problem solved." },
			...REIMAGE_RIO,
			{
				kind: "check",
				text: "Status LED still blinking 2 times, or does the code come back?",
				yes: "Swap the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: NI_FLASHING,
	},
	"roborio.status.3-blinks": {
		device: "roboRIO",
		led: "Status",
		state: "3 blinks, pause",
		meaning:
			"Safe mode. Only the services needed to update software run. Robot code does not run. Someone held reset for 5 seconds or more, or the image failed to boot.",
		steps: [
			"Press reset briefly, or power cycle, to leave safe mode.",
			{
				kind: "check",
				text: "Does it return to safe mode on its own (3 blinks)?",
				yes: "Continue.",
				no: "Problem solved.",
			},
			...REIMAGE_RIO,
			{
				kind: "check",
				text: "Still landing in safe mode after a fresh image?",
				yes: "Swap the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: WPILIB_IMAGING,
	},
	"roborio.status.4-blinks": {
		device: "roboRIO",
		led: "Status",
		state: "4 blinks, pause",
		meaning:
			"Robot code crashed twice without a reboot in between. NI says this is usually the controller running out of memory. Counted flashes with a pause are not the same as a continuous flash.",
		steps: [
			"Reboot the roboRIO.",
			{ kind: "check", text: "Status LED still blinking 4 times?", yes: "Continue.", no: "Problem solved." },
			"Have the team redeploy code and read the DS console for the crash.",
			{ kind: "check", text: "Does the 4-blink code repeat?", yes: "Continue.", no: "Problem solved." },
			...REIMAGE_RIO,
			{
				kind: "check",
				text: "Does it repeat after a reimage with known good code?",
				yes: "Swap the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.status.continuous": {
		device: "roboRIO",
		led: "Status",
		state: "Continuous flash, or solid after boot",
		meaning: "Unrecoverable error. The controller cannot boot its image. What that means depends on the model.",
		variants: [
			{
				label: "roboRIO 1",
				meaning: "The image on the internal flash is corrupt, or a software update was interrupted. The controller cannot boot.",
				steps: [
					"Power cycle once.",
					{ kind: "check", text: "Status LED still flashing?", yes: "Continue.", no: "Problem solved." },
					"Hold reset for 5 seconds to force safe mode. Safe mode shows 3 blinks with a pause.",
					"In safe mode, connect USB and reimage with the roboRIO Imaging Tool (Format Target).",
					{
						kind: "check",
						text: "Status LED still flashing, or will it not enter safe mode?",
						yes: "Continue.",
						no: "Problem solved.",
					},
					"Put NI's recovery.cfg alone on a FAT32 USB stick and plug it in.",
					"Hold reset while powering on, and release when the Status LED is solid.",
					"Wait about 60 seconds.",
					"Reimage with the roboRIO Imaging Tool (Format Target).",
					{
						kind: "check",
						text: "Status LED still flashing after recovery and reimage?",
						yes: "Swap the roboRIO.",
						no: "Problem solved.",
					},
				],
			},
			{
				label: "roboRIO 2",
				meaning: "The controller cannot read the microSD card. The card is missing, not clicked in, not imaged, or corrupt.",
				steps: [
					"Power off. Pull the microSD card and push it back in until it clicks and sits flush with the slot.",
					"Power on.",
					{ kind: "check", text: "Still flashing?", yes: "Continue.", no: "Problem solved." },
					"Reimage the card on a laptop with balenaEtcher or Raspberry Pi Imager. Use a fresh card if you have one.",
					"Put the card back, connect USB, and set the team number with the roboRIO Imaging Tool.",
					{ kind: "check", text: "Still flashing?", yes: "Continue.", no: "Problem solved." },
					"Open the case and blow out the SD slot with compressed air. Metal shavings in the slot cause this.",
					{
						kind: "check",
						text: "Does a freshly imaged card still fail?",
						yes: "Swap the roboRIO. The card reader is damaged.",
						no: "Problem solved.",
					},
				],
			},
		],
		defaultVariant: 1,
		source: WPILIB,
	},
	"roborio.radio.ignore": {
		device: "roboRIO",
		led: "Radio",
		state: "Any",
		meaning: "The FRC image does not drive this LED. It was for an NI USB radio that FRC never used.",
		steps: ["Ignore it. Radio state is on the radio's own LEDs."],
		source: WPILIB,
	},
	"roborio.comm.no-comms": {
		device: "roboRIO",
		led: "Comm",
		state: "Off",
		meaning: "No Driver Station heartbeat is reaching the roboRIO.",
		steps: [
			"On the radio, check SYS is solid (field link) and the RIO LED is lit (Ethernet link).",
			"Reseat the Ethernet cable between the roboRIO and the radio.",
			{ kind: "check", text: "Comm LED still off?", yes: "Continue.", no: "Problem solved." },
			"Swap the Ethernet cable.",
			{ kind: "check", text: "Comm LED still off?", yes: "Continue.", no: "Problem solved." },
			"On the DS, check the team number. A radio ping with no roboRIO ping points at the roboRIO or its cable.",
			"Confirm the roboRIO finished booting. Its Status LED is off when booted.",
			"Reboot the roboRIO, then the radio.",
			{
				kind: "check",
				text: "Comm LED still off with a known good cable and radio?",
				yes: "Reimage or swap the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.comm.no-code": {
		device: "roboRIO",
		led: "Comm",
		state: "Solid red",
		meaning:
			"The Driver Station is talking to the roboRIO but no robot program is running. Code may still be starting, may have crashed, or was never deployed.",
		steps: [
			"Wait. Code can take up to a minute to start after boot.",
			{ kind: "check", text: "Comm LED still solid red?", yes: "Continue.", no: "Problem solved." },
			"Read the DS console for a crash or exception.",
			"Have the team redeploy code. LabVIEW must be deployed with Run as Startup.",
			{ kind: "check", text: "Comm LED still solid red?", yes: "Continue.", no: "Problem solved." },
			"Reboot the roboRIO.",
			{ kind: "check", text: "Comm LED still solid red?", yes: "Continue.", no: "Problem solved." },
			"Check the image year matches the team's WPILib year. Code that deploys but never runs is often a year mismatch.",
			{ kind: "check", text: "Is the image year wrong?", yes: "Reimage the roboRIO.", no: "Problem solved." },
		],
		source: NI_RED,
	},
	"roborio.comm.e-stop": {
		device: "roboRIO",
		led: "Comm",
		state: "Blinking red",
		meaning:
			"The Driver Station E-Stopped the robot (space bar, or the field E-Stop). Outputs stay disabled until the roboRIO reboots.",
		steps: [
			"Confirm the field is safe and the FTA has cleared the stop.",
			"Reboot the roboRIO. Press reset or power cycle the robot; an E-Stop does not clear by disabling.",
			{
				kind: "check",
				text: "Does it E-Stop again with nobody pressing anything?",
				yes: "Check the DS laptop for a stuck space bar.",
				no: "Problem solved.",
			},
		],
		source: NI_RED,
	},
	"roborio.comm.ok": {
		device: "roboRIO",
		led: "Comm",
		state: "Solid green",
		meaning: "Good communication with the Driver Station and robot code is running.",
		steps: [
			{
				kind: "check",
				text: "Robot does not move when enabled?",
				yes: "Check the Mode LED and the Power LED.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.mode.disabled": {
		device: "roboRIO",
		led: "Mode",
		state: "Off",
		meaning: "Outputs are off. The robot is disabled, browned out, or E-Stopped.",
		steps: [
			"Expect Mode off between matches and before the match starts.",
			{ kind: "check", text: "Does the DS say enabled while Mode stays off?", yes: "Continue.", no: "Problem solved." },
			"Check the Power LED. Amber means brownout.",
			"Check the Comm LED. Blinking red means E-Stop.",
		],
		source: WPILIB,
	},
	"roborio.mode.auto": {
		device: "roboRIO",
		led: "Mode",
		state: "Solid orange",
		meaning: "Autonomous enabled. Outputs are live.",
		steps: [
			{
				kind: "check",
				text: "Robot does not move?",
				yes: "The fault is in code or on the CAN bus, not the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.mode.teleop": {
		device: "roboRIO",
		led: "Mode",
		state: "Solid green",
		meaning: "Teleop enabled. Outputs are live.",
		steps: [
			{
				kind: "check",
				text: "Robot does not respond?",
				yes: "Check the joysticks in the DS USB tab and the motor LEDs.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.mode.test": {
		device: "roboRIO",
		led: "Mode",
		state: "Solid red",
		meaning: "Test mode enabled from the Driver Station. The field never sends Test.",
		steps: [
			"Disable in the DS and select Teleop or Autonomous.",
			{
				kind: "check",
				text: "Does Test mode come back on its own?",
				yes: "Reboot the roboRIO.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.rsl.disabled": {
		device: "roboRIO",
		led: "RSL",
		state: "Solid",
		meaning: "Robot is on and disabled. The onboard LED mirrors the RSL output.",
		steps: [
			{
				kind: "check",
				text: "Is the external RSL dark while this is lit?",
				yes: "Check the RSL wiring and bulb.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.rsl.enabled": {
		device: "roboRIO",
		led: "RSL",
		state: "Blinking",
		meaning: "Robot is enabled.",
		steps: [
			{
				kind: "check",
				text: "Is the blinking rapid or erratic?",
				yes: "Check the battery. Power is low or unstable.",
				no: "Problem solved.",
			},
		],
		source: WPILIB,
	},
	"roborio.rsl.off": {
		device: "roboRIO",
		led: "RSL",
		state: "Off",
		meaning: "The roboRIO has no power, or the RSL output is not driven.",
		steps: [
			"Check the roboRIO Power LED. Off means no power to the roboRIO.",
			"Check the RSL is wired to the RSL port with its jumper in place.",
			{ kind: "check", text: "RSL still off?", yes: "Reboot the roboRIO.", no: "Problem solved." },
		],
		source: WPILIB,
	},
	"systemcore.power.ok": {
		device: "SystemCore",
		led: "Power",
		state: "Solid green",
		meaning: "Input power is good.",
		steps: [
			{
				kind: "check",
				text: "Robot has no comms?",
				yes: "Read the OLED screen for IP addresses and faults.",
				no: "Problem solved.",
			},
		],
		source: SC_SPEC,
	},
	"systemcore.power.off": {
		device: "SystemCore",
		led: "Power",
		state: "Off",
		meaning:
			"No input power, or the power leads are reversed. The input has reverse polarity protection, so a reversed lead shows as off.",
		steps: [
			"Check polarity at the power connector.",
			{ kind: "check", text: "Power LED still off?", yes: "Continue.", no: "Problem solved." },
			"Check the power lead at the source and the breaker or fuse.",
			{ kind: "check", text: "Power LED still off?", yes: "Continue.", no: "Problem solved." },
			"Swap the power cable.",
			{
				kind: "check",
				text: "Power LED still off with known good 12 V at the connector?",
				yes: "Swap the controller.",
				no: "Problem solved.",
			},
		],
		source: SC_SPEC,
	},
	"systemcore.mode.disabled": {
		device: "SystemCore",
		led: "Mode",
		state: "Solid yellow",
		meaning: "Robot is on and disabled.",
		steps: [
			"Expect solid yellow between matches.",
			{
				kind: "check",
				text: "Does the DS say enabled while Mode stays solid?",
				yes: "Check the Status LED for a brownout.",
				no: "Problem solved.",
			},
		],
		source: SC_SPEC,
	},
	"systemcore.mode.enabled": {
		device: "SystemCore",
		led: "Mode",
		state: "Blinking yellow",
		meaning: "Robot is on and enabled.",
		source: SC_SPEC,
	},
	"systemcore.mode.off": {
		device: "SystemCore",
		led: "Mode",
		state: "Off",
		meaning: "No power.",
		steps: ["See the Power LED. Check the power leads, polarity, and the breaker."],
		source: SC_SPEC,
	},
	"systemcore.status.ok": {
		device: "SystemCore",
		led: "Status",
		state: "Off",
		meaning: "No active faults.",
		source: SC_SPEC,
	},
	"systemcore.status.solid": {
		device: "SystemCore",
		led: "Status",
		state: "Solid red",
		meaning:
			"An uncleared hardware fault is active (overcurrent on a port, IO, I2C, USB, or IMU), or the display has faulted. The spec sheet also lists brownout protection here; newer OS releases show brownout as a fast blink.",
		steps: [
			"Read the OLED screen. It names the fault.",
			"Open the web dashboard at robot.local over USB or Wi-Fi. The faults panel in the header shows the name and count.",
			"For an overcurrent on a port, unplug that device, check its wiring for a short, and plug it back in.",
			"Power cycle to clear.",
			{ kind: "check", text: "Status LED still solid red with nothing plugged in?", yes: "Continue.", no: "Problem solved." },
			"Swap the controller and report it in the SystemcoreTesting GitHub issues.",
		],
		source: SC_SPEC,
	},
	"systemcore.status.slow-blink": {
		device: "SystemCore",
		led: "Status",
		state: "Slow red blink",
		meaning: "Display hardware fault. The OLED screen is not responding.",
		steps: [
			"Power cycle.",
			{ kind: "check", text: "Does the slow blink continue with the screen dark?", yes: "Continue.", no: "Problem solved." },
			"Swap the controller if you have a spare, and report it in the SystemcoreTesting GitHub issues.",
		],
		source: SC_OS,
	},
	"systemcore.status.fast-blink": {
		device: "SystemCore",
		led: "Status",
		state: "Fast red blink",
		meaning:
			"A CAN bus is unavailable or down, or the controller is in brownout. The OLED shows a health box per CAN bus.",
		steps: [
			"Read the OLED. A single flashing pixel means that bus is unavailable, an empty box means the bus is up but down, a blinking box means it is healthy.",
			"For a down bus, check CANH and CANL wiring and termination on that bus, and look for a shorted device.",
			{ kind: "check", text: "Still a fast red blink?", yes: "Continue.", no: "Problem solved." },
			"Check battery voltage. The default brownout is 6.75 V, recovery 7.5 V.",
			"Swap the battery and check the main power connections.",
			"Power cycle.",
			{
				kind: "check",
				text: "Still a fast red blink?",
				yes: "Recheck the CAN buses on the OLED health boxes.",
				no: "Problem solved.",
			},
		],
		source: SC_OS,
	},
} as const satisfies Record<string, StatusLightHelp>;
