// Status light help: REV devices. See shared.ts for the step rules.

import { type StatusLightHelp, REV_FLEX, REV_MAX, REV_PDH, REV_PH } from "./shared";

export const revHelp = {
	"revsparkmax.brushless-mode.brake-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Cyan blink",
		meaning:
			"Brushless motor type, brake mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain (yellow, green) and the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID. The REV Hardware Client lists what the bus sees.",
			"Look for a CAN fault (orange and yellow blink) on another controller in the chain.",
			{ kind: "check", text: "Still blinking cyan?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushless-mode.brake-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Cyan solid",
		meaning: "Brushless motor type, brake mode, valid signal. Normal when enabled with zero output.",
		steps: [
			{ kind: "check", text: "Does the motor move when commanded?", yes: "Normal. Zero output looks like this.", no: "Continue." },
			"Check the three phase wires at the motor and controller.",
			"Reseat the encoder cable at the SPARK MAX data port. A brushless motor will not run without its sensor.",
			{ kind: "check", text: "Is the encoder cable or connector damaged?", yes: "Replace the motor.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushless-mode.coast-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Magenta blink",
		meaning:
			"Brushless motor type, coast mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain (yellow, green) and the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID. The REV Hardware Client lists what the bus sees.",
			{ kind: "check", text: "Still blinking magenta?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushless-mode.coast-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Magenta solid",
		meaning: "Brushless motor type, coast mode, valid signal. Normal when enabled with zero output.",
		steps: [
			{ kind: "check", text: "Does the motor move when commanded?", yes: "Normal. Zero output looks like this.", no: "Continue." },
			"Check the three phase wires at the motor and controller.",
			"Reseat the encoder cable at the SPARK MAX data port. A brushless motor will not run without its sensor.",
			{ kind: "check", text: "Is the encoder cable or connector damaged?", yes: "Replace the motor.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.brake-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Blue blink",
		meaning:
			"Brushed motor type, brake mode, no valid control signal. If a NEO or other brushless motor is attached, the motor type is wrong.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Stop. Set the type to brushless.", no: "Continue." },
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain or the PWM cable and the CAN ID in code.",
			{ kind: "check", text: "Still blinking blue?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.brake-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Blue solid",
		meaning: "Brushed motor type, brake mode, valid signal.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Do not enable. Set the type to brushless.", no: "Normal. Brushed brake, valid signal." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.coast-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Yellow blink",
		meaning:
			"Brushed motor type, coast mode, no valid control signal. If a brushless motor is attached, the motor type is wrong.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Stop. Set the type to brushless.", no: "Continue." },
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain or the PWM cable and the CAN ID in code.",
			{ kind: "check", text: "Still blinking yellow?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.coast-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Yellow solid",
		meaning: "Brushed motor type, coast mode, valid signal.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Do not enable. Set the type to brushless.", no: "Normal. Brushed coast, valid signal." },
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.sensor-fault": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and magenta slow blink",
		meaning:
			"Sensor fault. Wrong sensor type configured, encoder cable unplugged or damaged, or the wrong sensor connected.",
		steps: [
			"Reseat the encoder cable at the SPARK MAX data port.",
			{ kind: "check", text: "Still blinking orange and magenta?", yes: "Continue.", no: "Problem solved." },
			{ kind: "check", text: "Is the sensor cable or connector damaged?", yes: "Replace the motor.", no: "Continue." },
			"In the REV Hardware Client, confirm the sensor type matches the motor. NEO uses a hall sensor.",
			"Power cycle.",
			{ kind: "check", text: "Still faulting with a known good motor?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.12v-missing": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and blue slow blink",
		meaning: "No 12 V on the power input. The controller is powered only by USB and will not drive the motor.",
		steps: [
			{ kind: "check", text: "Is the controller on the bench over USB only?", yes: "Expected. It needs 12 V to drive.", no: "Continue." },
			"Check the power leads at the PDP or PDH and the breaker.",
			"Check the crimp and connector at the controller.",
			{ kind: "check", text: "Still blinking orange and blue?", yes: "Trace the 12 V feed to this controller.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.gate-driver-fault": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and cyan slow blink",
		meaning: "Internal motor drive circuit fault.",
		steps: [
			"Power cycle.",
			{ kind: "check", text: "Does the fault come back?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.can-fault": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and yellow slow blink",
		meaning: "The controller sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wires at this controller and its neighbours. Wiggle the connectors.",
			"Check termination at both ends of the bus.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
			{ kind: "check", text: "Still blinking orange and yellow?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.corrupt-firmware": {
		device: "SPARK MAX",
		led: "Status",
		state: "Dark",
		meaning: "Firmware failed to load. The LED stays dark even with power.",
		steps: [
			"Confirm 12 V is present. A dark LED is also just no power.",
			"Enter Recovery Mode: hold the Mode button while plugging in USB, then reflash firmware in the REV Hardware Client.",
			{ kind: "check", text: "Will it take firmware?", yes: "Problem solved.", no: "Swap the controller." },
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.identify": {
		device: "SPARK MAX",
		led: "Status",
		state: "White and magenta fast blink",
		meaning: "Someone pressed Identify in the REV Hardware Client. Cosmetic.",
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.can-firmware-updating-v1-5-0": {
		device: "SPARK MAX",
		led: "Status",
		state: "White and yellow blink",
		meaning: "Firmware is being written over CAN.",
		steps: [
			"Do not power off. Wait for it to finish.",
			{ kind: "check", text: "Stuck here for minutes?", yes: "Power cycle and update over USB.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.can-firmware-updating-v1-4-0": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green and magenta blink",
		meaning: "Firmware is being written over CAN (older bootloader).",
		steps: [
			"Do not power off. Wait for it to finish.",
			{ kind: "check", text: "Stuck here for minutes?", yes: "Power cycle and update over USB.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.can-firmware-retry": {
		device: "SPARK MAX",
		led: "Status",
		state: "White and blue blink",
		meaning: "A CAN firmware update failed and the controller is retrying.",
		steps: [
			"Keep power on and let it retry.",
			{ kind: "check", text: "Still stuck here?", yes: "Update over USB in the REV Hardware Client.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.usb-device-firmware-update": {
		device: "SPARK MAX",
		led: "Status",
		state: "Dark",
		meaning: "USB firmware update mode. The REV Hardware Client is flashing it.",
		steps: ["Finish the update in the REV Hardware Client, then power cycle."],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.recovery-mode": {
		device: "SPARK MAX",
		led: "Status",
		state: "Dark",
		meaning: "Recovery mode. Used to reflash a controller whose firmware is corrupt.",
		steps: ["Connect USB and flash firmware in the REV Hardware Client.", "Power cycle when done."],
		source: REV_MAX,
	},
	"revsparkmax.movement.partial-forward": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green blink",
		meaning: "Driving forward at partial output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.full-forward": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green solid",
		meaning: "Driving forward at full output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.partial-reverse": {
		device: "SPARK MAX",
		led: "Status",
		state: "Red blink",
		meaning: "Driving reverse at partial output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.full-reverse": {
		device: "SPARK MAX",
		led: "Status",
		state: "Red solid",
		meaning: "Driving reverse at full output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.forward-limit": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green and white blink",
		meaning: "The forward limit switch or soft limit is active. Forward output is blocked.",
		steps: [
			{ kind: "check", text: "Is the mechanism sitting on the forward limit?", yes: "Move it off the limit.", no: "Continue." },
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			{ kind: "check", text: "Still blocked forward?", yes: "Fix the switch wiring or polarity.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkmax.movement.reverse-limit": {
		device: "SPARK MAX",
		led: "Status",
		state: "Red and white blink",
		meaning: "The reverse limit switch or soft limit is active. Reverse output is blocked.",
		steps: [
			{ kind: "check", text: "Is the mechanism sitting on the reverse limit?", yes: "Move it off the limit.", no: "Continue." },
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			{ kind: "check", text: "Still blocked in reverse?", yes: "Fix the switch wiring or polarity.", no: "Problem solved." },
		],
		source: REV_MAX,
	},
	"revsparkflex.brushless-mode.brake-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Cyan blink",
		meaning:
			"Brushless motor type, brake mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain (yellow, green) and the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID. The REV Hardware Client lists what the bus sees.",
			{ kind: "check", text: "Still blinking cyan?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushless-mode.brake-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Cyan solid",
		meaning: "Brushless motor type, brake mode, valid signal. Normal when enabled with zero output.",
		steps: [
			{ kind: "check", text: "Does the motor move when commanded?", yes: "Normal. Zero output looks like this.", no: "Continue." },
			"Check the Vortex is seated on the Flex.",
			"Clean the dock connector.",
			{ kind: "check", text: "Still not moving?", yes: "Swap the Vortex or the controller.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushless-mode.coast-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Magenta blink",
		meaning:
			"Brushless motor type, coast mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain (yellow, green) and the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID.",
			{ kind: "check", text: "Still blinking magenta?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushless-mode.coast-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Magenta solid",
		meaning: "Brushless motor type, coast mode, valid signal. Normal when enabled with zero output.",
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.brake-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Blue blink",
		meaning:
			"Brushed motor type, brake mode, no valid control signal. If a Vortex or NEO is attached, the motor type is wrong.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Stop. Set the type to brushless.", no: "Continue." },
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain or the PWM cable and the CAN ID in code.",
			{ kind: "check", text: "Still blinking blue?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.brake-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Blue solid",
		meaning: "Brushed motor type, brake mode, valid signal.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Do not enable. Set the type to brushless.", no: "Normal. Brushed brake, valid signal." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.coast-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Yellow blink",
		meaning:
			"Brushed motor type, coast mode, no valid control signal. If a brushless motor is attached, the motor type is wrong.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Stop. Set the type to brushless.", no: "Continue." },
			{ kind: "check", text: "Is the robot enabled?", no: "Normal while disabled.", yes: "Continue." },
			"Check the CAN chain or the PWM cable and the CAN ID in code.",
			{ kind: "check", text: "Still blinking yellow?", yes: "The controller is fine. Fix code or comms.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.coast-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Yellow solid",
		meaning: "Brushed motor type, coast mode, valid signal.",
		steps: [
			{ kind: "check", text: "Is a brushless motor attached?", yes: "Do not enable. Set the type to brushless.", no: "Normal. Brushed coast, valid signal." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.sensor-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and magenta slow blink",
		meaning:
			"Sensor fault. Wrong sensor type configured, sensor cable unplugged or damaged, or the wrong sensor connected.",
		steps: [
			"Reseat the motor on the Flex dock. Reseat the sensor cable if an external motor is used.",
			{ kind: "check", text: "Still blinking orange and magenta?", yes: "Continue.", no: "Problem solved." },
			{ kind: "check", text: "Is the motor a Vortex or NEO with a bad sensor?", yes: "Replace the motor.", no: "Continue." },
			{ kind: "check", text: "Is a separate brushed encoder cable damaged?", yes: "Swap that cable.", no: "Continue." },
			"In the REV Hardware Client, confirm the sensor type matches the motor.",
			"Power cycle.",
			{ kind: "check", text: "Still faulting with a known good motor?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.12v-missing": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and blue slow blink",
		meaning: "No 12 V on the power input. The controller is powered only by USB and will not drive the motor.",
		steps: [
			{ kind: "check", text: "Is the controller on the bench over USB only?", yes: "Expected. It needs 12 V to drive.", no: "Continue." },
			"Check the power leads at the PDP or PDH and the breaker.",
			"Check the connector at the controller.",
			{ kind: "check", text: "Still blinking orange and blue?", yes: "Trace the 12 V feed to this controller.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.gate-driver-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and cyan slow blink",
		meaning: "Internal motor drive circuit fault.",
		steps: [
			"Power cycle.",
			{ kind: "check", text: "Does the fault come back?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.can-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and yellow slow blink",
		meaning: "The controller sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wires at this controller and its neighbours. Wiggle the connectors.",
			"Check termination at both ends of the bus.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
			{ kind: "check", text: "Still blinking orange and yellow?", yes: "Swap the controller.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.temperature-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and green slow blink",
		meaning:
			"Temperature cutoff. The controller or motor overheated and output is cut. It clears on its own after cooling.",
		steps: [
			"Let it cool. Do not enable until the blink stops.",
			"Check for a stalled or binding mechanism.",
			"Check airflow around the motor and controller.",
			"Have the team add or lower current limits in code.",
			{ kind: "check", text: "Does it overheat again after cooling?", yes: "Find the mechanical bind or high load.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.corrupt-firmware": {
		device: "SPARK Flex",
		led: "Status",
		state: "Dark",
		meaning: "Firmware failed to load. The LED stays dark even with power.",
		steps: [
			"Confirm 12 V is present. A dark LED is also just no power.",
			"Enter Recovery Mode: hold the Mode button while plugging in USB, then reflash firmware in the REV Hardware Client.",
			{ kind: "check", text: "Will it take firmware?", yes: "Problem solved.", no: "Swap the controller." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.identify": {
		device: "SPARK Flex",
		led: "Status",
		state: "White and magenta fast blink",
		meaning: "Someone pressed Identify in the REV Hardware Client. Cosmetic.",
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.can-firmware-updating": {
		device: "SPARK Flex",
		led: "Status",
		state: "White and yellow blink",
		meaning: "Firmware is being written over CAN.",
		steps: [
			"Do not power off. Wait for it to finish.",
			{ kind: "check", text: "Stuck here for minutes?", yes: "Power cycle and update over USB.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.can-firmware-retry": {
		device: "SPARK Flex",
		led: "Status",
		state: "White and blue blink",
		meaning: "A CAN firmware update failed and the controller is retrying.",
		steps: [
			"Keep power on and let it retry.",
			{ kind: "check", text: "Still stuck here?", yes: "Update over USB in the REV Hardware Client.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.usb-device-firmware-update": {
		device: "SPARK Flex",
		led: "Status",
		state: "Dark",
		meaning: "USB firmware update mode. The REV Hardware Client is flashing it.",
		steps: ["Finish the update in the REV Hardware Client, then power cycle."],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.recovery-mode": {
		device: "SPARK Flex",
		led: "Status",
		state: "Dark",
		meaning: "Recovery mode. Used to reflash a controller whose firmware is corrupt.",
		steps: ["Connect USB and flash firmware in the REV Hardware Client.", "Power cycle when done."],
		source: REV_FLEX,
	},
	"revsparkflex.movement.partial-forward": {
		device: "SPARK Flex",
		led: "Status",
		state: "Green blink",
		meaning: "Driving forward at partial output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.full-forward": {
		device: "SPARK Flex",
		led: "Status",
		state: "Green solid",
		meaning: "Driving forward at full output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.partial-reverse": {
		device: "SPARK Flex",
		led: "Status",
		state: "Red blink",
		meaning: "Driving reverse at partial output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.full-reverse": {
		device: "SPARK Flex",
		led: "Status",
		state: "Red solid",
		meaning: "Driving reverse at full output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.forward-limit": {
		device: "SPARK Flex",
		led: "Status",
		state: "Green and white blink",
		meaning: "The forward limit switch or soft limit is active. Forward output is blocked.",
		steps: [
			{ kind: "check", text: "Is the mechanism sitting on the forward limit?", yes: "Move it off the limit.", no: "Continue." },
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			{ kind: "check", text: "Still blocked forward?", yes: "Fix the switch wiring or polarity.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revsparkflex.movement.reverse-limit": {
		device: "SPARK Flex",
		led: "Status",
		state: "Red and white blink",
		meaning: "The reverse limit switch or soft limit is active. Reverse output is blocked.",
		steps: [
			{ kind: "check", text: "Is the mechanism sitting on the reverse limit?", yes: "Move it off the limit.", no: "Continue." },
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			{ kind: "check", text: "Still blocked in reverse?", yes: "Fix the switch wiring or polarity.", no: "Problem solved." },
		],
		source: REV_FLEX,
	},
	"revpowerdistributionhub.general-status.no-communication-established": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Blue solid",
		meaning: "Powered, no CAN communication yet. Normal for the first seconds after boot.",
		steps: [
			"Wait for the roboRIO to boot and code to start.",
			{ kind: "check", text: "Does it stay blue?", yes: "Continue.", no: "Problem solved." },
			"Check the CAN wiring to the PDH and the termination switch on the PDH.",
			"Confirm robot code is running. The roboRIO Comm LED is green.",
			{ kind: "check", text: "Still blue?", yes: "Trace CAN from the roboRIO to the PDH.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.roborio-communication-established": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Green solid",
		meaning: "Communicating with the roboRIO. Normal.",
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.connected-to-rev-hardware-client": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Cyan solid",
		meaning: "A laptop running the REV Hardware Client is connected over USB-C. Fine in the pit.",
		steps: ["Unplug the USB cable before the robot goes to the field."],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.keep-alive-timeout": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Magenta blink",
		meaning:
			"The PDH had communication with the roboRIO and lost it. The roboRIO stopped sending heartbeat frames.",
		steps: [
			"Check whether the roboRIO rebooted or code crashed. Read the Comm LED.",
			"Check the CAN wiring between the roboRIO and the PDH.",
			"Power cycle.",
			{ kind: "check", text: "Still blinking magenta?", yes: "Fix the roboRIO comms or CAN wiring.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.low-battery": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and blue blink",
		meaning: "Battery voltage is low.",
		steps: [
			"Swap the battery.",
			{ kind: "check", text: "Still blinking orange and blue?", yes: "Continue.", no: "Problem solved." },
			"Check the main battery connections and main breaker for heat or looseness.",
			{ kind: "check", text: "Still low after a good battery?", yes: "Fix the main leads or breaker.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.can-fault": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and yellow blink",
		meaning: "The PDH sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wiring at the PDH and its neighbours.",
			"Check the termination switch. On if the PDH ends the bus, off if not.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
			{ kind: "check", text: "Still blinking orange and yellow?", yes: "Swap the PDH.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.hardware-fault": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and cyan blink",
		meaning: "The PDH detected an internal hardware fault.",
		steps: [
			"Power cycle.",
			"Inspect for metal debris and damage.",
			{ kind: "check", text: "Does the fault come back?", yes: "Swap the PDH.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.device-over-current": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and magenta blink",
		meaning: "The PDH itself is over its current limit.",
		steps: [
			"Look for a shorted channel or a stalled motor.",
			"Reduce load.",
			"Check the main breaker and battery leads.",
			{ kind: "check", text: "Still over current?", yes: "Find the short or stall on a channel.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.channel-status.has-voltage-and-normal-operation": {
		device: "Power Distribution Hub",
		led: "Channel",
		state: "Off",
		meaning: "The channel has voltage and no fault. Normal.",
		source: REV_PDH,
	},
	"revpowerdistributionhub.channel-status.no-voltage-and-active-fault": {
		device: "Power Distribution Hub",
		led: "Channel",
		state: "Red solid",
		meaning: "The channel has no output voltage. The breaker is tripped, missing, or not seated.",
		steps: [
			"Press the breaker back in and check it is seated.",
			{ kind: "check", text: "Still no voltage on the channel?", yes: "Continue.", no: "Problem solved." },
			"Swap the breaker.",
			{ kind: "check", text: "Still no voltage?", yes: "Check the channel load for a short.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.channel-status.sticky-fault": {
		device: "Power Distribution Hub",
		led: "Channel",
		state: "Red blink",
		meaning: "A fault happened earlier on this channel and has not been cleared. The channel may be working now.",
		steps: [
			"Check the breaker is seated.",
			"Clear sticky faults from the REV Hardware Client or from code.",
			{ kind: "check", text: "Does the fault come back?", yes: "Find the intermittent short or tripping breaker.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.switched-channel.has-voltage-and-normal-operation": {
		device: "Power Distribution Hub",
		led: "Switched channel",
		state: "Off",
		meaning: "The switched channel has voltage and no fault. Normal.",
		source: REV_PDH,
	},
	"revpowerdistributionhub.switched-channel.no-voltage-and-active-fault": {
		device: "Power Distribution Hub",
		led: "Switched channel",
		state: "Red solid",
		meaning: "The switched channel has no output voltage. The fuse is blown or missing.",
		steps: [
			"Check the fuse is present and seated.",
			"Replace the fuse.",
			{ kind: "check", text: "Still no voltage on the switched channel?", yes: "Check the load for a short.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.switched-channel.sticky-fault": {
		device: "Power Distribution Hub",
		led: "Switched channel",
		state: "Red blink",
		meaning: "A fault happened earlier on the switched channel and has not been cleared.",
		steps: [
			"Check the fuse.",
			"Clear sticky faults from the REV Hardware Client or from code.",
			{ kind: "check", text: "Does the fault come back?", yes: "Find the intermittent short on that channel.", no: "Problem solved." },
		],
		source: REV_PDH,
	},
	"revpneumaticshub.general-status.no-communication-established": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Blue solid",
		meaning: "Powered, no CAN communication yet. Normal for the first seconds after boot.",
		steps: [
			"Wait for the roboRIO to boot and code to start.",
			{ kind: "check", text: "Does it stay blue?", yes: "Continue.", no: "Problem solved." },
			"Check the CAN wiring to the hub and the termination switch.",
			"Confirm the code creates a pneumatics object for the REV hub type.",
			{ kind: "check", text: "Still blue?", yes: "Trace CAN from the roboRIO to the hub.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.roborio-communication-established": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Green solid",
		meaning: "Communicating with the roboRIO. Normal.",
		source: REV_PH,
	},
	"revpneumaticshub.general-status.secondary-heartbeat": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Cyan solid",
		meaning: "A laptop running the REV Hardware Client is connected over USB-C. Fine in the pit.",
		steps: ["Unplug the USB cable before the robot goes to the field."],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.keep-alive-timeout": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Magenta blink",
		meaning: "The hub had communication with the roboRIO and lost it.",
		steps: [
			"Check whether the roboRIO rebooted or code crashed. Read the Comm LED.",
			"Check the CAN wiring to the hub.",
			"Power cycle.",
			{ kind: "check", text: "Still blinking magenta?", yes: "Fix the roboRIO comms or CAN wiring.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.hardware-fault": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and cyan blink",
		meaning: "The hub detected an internal hardware fault.",
		steps: [
			"Power cycle.",
			"Inspect for metal debris and damage.",
			{ kind: "check", text: "Does the fault come back?", yes: "Swap the hub.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.can-fault": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and yellow blink",
		meaning: "The hub sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wiring at the hub and its neighbours.",
			"Check the termination switch.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
			{ kind: "check", text: "Still blinking orange and yellow?", yes: "Swap the hub.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.compressor-over-current": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and green blink",
		meaning: "The compressor output is drawing too much current.",
		steps: [
			"Check the compressor wiring for a short.",
			"Check the compressor turns freely and is not seized.",
			"Let it cool, then power cycle.",
			{ kind: "check", text: "Still over current on the compressor?", yes: "Replace the compressor or fix its wiring.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.device-over-current": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and magenta blink",
		meaning: "The hub is over its current limit, usually on a solenoid output.",
		steps: [
			"Unplug solenoids one at a time to find the shorted one.",
			{ kind: "check", text: "Did unplugging one clear it?", yes: "Fix or replace that solenoid.", no: "Continue." },
			"Check the solenoid voltage setting matches the solenoids. It is 12 V or 24 V.",
			"Power cycle.",
			{ kind: "check", text: "Still over current?", yes: "Fix the shorted solenoid output.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.compressor-status.compressor-off": {
		device: "Pneumatic Hub",
		led: "Compressor",
		state: "Off",
		meaning: "The compressor output is off.",
		steps: [
			{ kind: "check", text: "Should the compressor be running now?", yes: "Continue.", no: "Normal. It is at pressure or disabled." },
			"Check the pressure switch wiring.",
			"Check the code enables the compressor.",
			{ kind: "check", text: "Still off when it should run?", yes: "Fix the pressure switch or code.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.compressor-status.compressor-on": {
		device: "Pneumatic Hub",
		led: "Compressor",
		state: "Green solid",
		meaning: "The compressor output is on.",
		steps: [
			{ kind: "check", text: "Is the compressor silent with this LED on?", yes: "Continue.", no: "Normal. The output is on." },
			"Check the compressor wiring.",
			{ kind: "check", text: "Still silent?", yes: "Replace the compressor.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.solenoid-status.solenoid-off": {
		device: "Pneumatic Hub",
		led: "Solenoid",
		state: "Off",
		meaning: "That solenoid channel is not energized.",
		steps: [
			{ kind: "check", text: "Should this solenoid be on now?", yes: "Continue.", no: "Normal. It is commanded off." },
			"Check the code commands this channel on.",
			"Confirm the channel number matches the wiring.",
			{ kind: "check", text: "Still off when commanded on?", yes: "Fix the code or the channel number.", no: "Problem solved." },
		],
		source: REV_PH,
	},
	"revpneumaticshub.solenoid-status.solenoid-on": {
		device: "Pneumatic Hub",
		led: "Solenoid",
		state: "Green solid",
		meaning: "That solenoid channel is energized.",
		steps: [
			{ kind: "check", text: "Does the cylinder move with this LED on?", yes: "Normal. The output is energized.", no: "Continue." },
			"Check air pressure at the cylinder.",
			"Check the solenoid wiring.",
			"Check the solenoid voltage setting matches the solenoid.",
			{ kind: "check", text: "Still not moving?", yes: "Replace the solenoid or cylinder.", no: "Problem solved." },
		],
		source: REV_PH,
	},
} as const satisfies Record<string, StatusLightHelp>;
