// Status light help: REV devices. See shared.ts for the step rules.

import { type StatusLightHelp, REV_FLEX, REV_MAX, REV_PDH, REV_PH } from "./shared";

export const revHelp = {
	"revsparkmax.brushless-mode.brake-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Cyan blink",
		meaning:
			"Brushless motor type, brake mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			"Normal while the robot is disabled.",
			"If enabled and still blinking: check the CAN chain (yellow, green) or the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID. The REV Hardware Client lists what the bus sees.",
			"Look for a CAN fault (orange and yellow blink) on another controller in the chain.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushless-mode.brake-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Cyan solid",
		meaning: "Brushless motor type, brake mode, valid signal. Normal when enabled with zero output.",
		steps: [
			"If the motor does not move when commanded, check the three phase wires and the encoder cable. A brushless motor will not run without its sensor.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushless-mode.coast-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Magenta blink",
		meaning:
			"Brushless motor type, coast mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			"Normal while the robot is disabled.",
			"If enabled and still blinking: check the CAN chain (yellow, green) or the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID. The REV Hardware Client lists what the bus sees.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushless-mode.coast-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Magenta solid",
		meaning: "Brushless motor type, coast mode, valid signal. Normal when enabled with zero output.",
		steps: [
			"If the motor does not move when commanded, check the phase wires and the encoder cable.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.brake-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Blue blink",
		meaning:
			"Brushed motor type, brake mode, no valid control signal. If a NEO or other brushless motor is attached, the motor type is wrong.",
		steps: [
			"Normal while disabled if a brushed motor is attached.",
			"If a brushless motor is attached: stop. Running a brushless motor in brushed mode damages it. Set the motor type to brushless in code or the REV Hardware Client.",
			"If enabled and still blinking: check the CAN chain or PWM cable and the CAN ID in code.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.brake-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Blue solid",
		meaning: "Brushed motor type, brake mode, valid signal.",
		steps: [
			"If a brushless motor is attached, do not enable. Set the motor type to brushless first.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.coast-no-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Yellow blink",
		meaning:
			"Brushed motor type, coast mode, no valid control signal. If a brushless motor is attached, the motor type is wrong.",
		steps: [
			"Normal while disabled if a brushed motor is attached.",
			"If a brushless motor is attached: stop. Set the motor type to brushless before enabling.",
			"If enabled and still blinking: check the CAN chain or PWM cable and the CAN ID in code.",
		],
		source: REV_MAX,
	},
	"revsparkmax.brushed-mode.coast-valid-signal": {
		device: "SPARK MAX",
		led: "Status",
		state: "Yellow solid",
		meaning: "Brushed motor type, coast mode, valid signal.",
		steps: [
			"If a brushless motor is attached, do not enable. Set the motor type to brushless first.",
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.sensor-fault": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and magenta slow blink",
		meaning:
			"Sensor fault. Wrong sensor type configured, encoder cable unplugged or damaged, or the wrong sensor connected.",
		steps: [
			"Reseat the encoder cable at the SPARK MAX data port and at the motor.",
			"Check the cable for damage. Swap it.",
			"In the REV Hardware Client, confirm the sensor type matches the motor (hall sensor for NEO).",
			"Power cycle.",
			"If it persists with a known good cable and motor, swap the controller.",
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.12v-missing": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and blue slow blink",
		meaning: "No 12 V on the power input. The controller is powered only by USB and will not drive the motor.",
		steps: [
			"Check the power leads at the PDP or PDH and the breaker.",
			"Check the crimp or connector at the controller.",
			"On the bench over USB this is expected.",
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.gate-driver-fault": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and cyan slow blink",
		meaning: "Internal motor drive circuit fault.",
		steps: ["Power cycle.", "If it comes back, swap the controller. REV asks you to contact them if it persists."],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.can-fault": {
		device: "SPARK MAX",
		led: "Status",
		state: "Orange and yellow slow blink",
		meaning: "The controller sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wires at this controller and its neighbours.",
			"Check termination at the end of the bus.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
		],
		source: REV_MAX,
	},
	"revsparkmax.fault-conditions.corrupt-firmware": {
		device: "SPARK MAX",
		led: "Status",
		state: "Dark",
		meaning: "Firmware failed to load. The LED stays dark even with power.",
		steps: [
			"Confirm 12 V is present. A dark LED is also just no power.",
			"Enter Recovery Mode: hold the Mode button while plugging in USB, then reflash firmware in the REV Hardware Client.",
			"If it will not take firmware, swap the controller.",
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.identify": {
		device: "SPARK MAX",
		led: "Status",
		state: "White and magenta fast blink",
		meaning: "Someone pressed Identify in the REV Hardware Client. Cosmetic.",
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.can-firmware-updating-v1-5-0": {
		device: "SPARK MAX",
		led: "Status",
		state: "White and yellow blink",
		meaning: "Firmware is being written over CAN.",
		steps: [
			"Do not power off. Wait for it to finish.",
			"If it sits there for minutes, power cycle and update over USB instead.",
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.can-firmware-updating-v1-4-0": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green and magenta blink",
		meaning: "Firmware is being written over CAN (older bootloader).",
		steps: [
			"Do not power off. Wait for it to finish.",
			"If it sits there for minutes, power cycle and update over USB instead.",
		],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.can-firmware-retry": {
		device: "SPARK MAX",
		led: "Status",
		state: "White and blue blink",
		meaning: "A CAN firmware update failed and the controller is retrying.",
		steps: ["Keep power on and let it retry.", "If it stays here, update over USB with the REV Hardware Client."],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.usb-device-firmware-update": {
		device: "SPARK MAX",
		led: "Status",
		state: "Dark",
		meaning: "USB firmware update mode. The REV Hardware Client is flashing it.",
		steps: ["Finish the update in the Hardware Client, then power cycle."],
		source: REV_MAX,
	},
	"revsparkmax.identification-updating-and-recovery.recovery-mode": {
		device: "SPARK MAX",
		led: "Status",
		state: "Dark",
		meaning: "Recovery mode. Used to reflash a controller whose firmware is corrupt.",
		steps: ["Connect USB and flash firmware in the REV Hardware Client.", "Power cycle when done."],
		source: REV_MAX,
	},
	"revsparkmax.movement.partial-forward": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green blink",
		meaning: "Driving forward at partial output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.full-forward": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green solid",
		meaning: "Driving forward at full output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.partial-reverse": {
		device: "SPARK MAX",
		led: "Status",
		state: "Red blink",
		meaning: "Driving reverse at partial output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.full-reverse": {
		device: "SPARK MAX",
		led: "Status",
		state: "Red solid",
		meaning: "Driving reverse at full output.",
		source: REV_MAX,
	},
	"revsparkmax.movement.forward-limit": {
		device: "SPARK MAX",
		led: "Status",
		state: "Green and white blink",
		meaning: "The forward limit switch or soft limit is active. Forward output is blocked.",
		steps: [
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			"Move the mechanism off the limit.",
		],
		source: REV_MAX,
	},
	"revsparkmax.movement.reverse-limit": {
		device: "SPARK MAX",
		led: "Status",
		state: "Red and white blink",
		meaning: "The reverse limit switch or soft limit is active. Reverse output is blocked.",
		steps: [
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			"Move the mechanism off the limit.",
		],
		source: REV_MAX,
	},
	"revsparkflex.brushless-mode.brake-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Cyan blink",
		meaning:
			"Brushless motor type, brake mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			"Normal while the robot is disabled.",
			"If enabled and still blinking: check the CAN chain (yellow, green) or the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID. The REV Hardware Client lists what the bus sees.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushless-mode.brake-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Cyan solid",
		meaning: "Brushless motor type, brake mode, valid signal. Normal when enabled with zero output.",
		steps: [
			"If the motor does not move when commanded, check the motor is seated on the Flex and the dock connector is clean.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushless-mode.coast-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Magenta blink",
		meaning:
			"Brushless motor type, coast mode, no valid control signal. Powered, but nothing is commanding it: robot disabled, no CAN or PWM frames, or no code.",
		steps: [
			"Normal while the robot is disabled.",
			"If enabled and still blinking: check the CAN chain (yellow, green) or the PWM cable to this controller.",
			"Confirm the code creates this motor with the right CAN ID.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushless-mode.coast-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Magenta solid",
		meaning: "Brushless motor type, coast mode, valid signal. Normal when enabled with zero output.",
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.brake-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Blue blink",
		meaning:
			"Brushed motor type, brake mode, no valid control signal. If a Vortex or NEO is attached, the motor type is wrong.",
		steps: [
			"If a brushless motor is attached: stop. Running a brushless motor in brushed mode damages it. Set the motor type to brushless.",
			"Normal while disabled if a brushed motor is attached.",
			"If enabled and still blinking: check the CAN chain or PWM cable and the CAN ID in code.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.brake-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Blue solid",
		meaning: "Brushed motor type, brake mode, valid signal.",
		steps: [
			"If a brushless motor is attached, do not enable. Set the motor type to brushless first.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.coast-no-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Yellow blink",
		meaning:
			"Brushed motor type, coast mode, no valid control signal. If a brushless motor is attached, the motor type is wrong.",
		steps: [
			"If a brushless motor is attached: stop. Set the motor type to brushless before enabling.",
			"Normal while disabled if a brushed motor is attached.",
			"If enabled and still blinking: check the CAN chain or PWM cable and the CAN ID in code.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.brushed-mode.coast-valid-signal": {
		device: "SPARK Flex",
		led: "Status",
		state: "Yellow solid",
		meaning: "Brushed motor type, coast mode, valid signal.",
		steps: [
			"If a brushless motor is attached, do not enable. Set the motor type to brushless first.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.sensor-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and magenta slow blink",
		meaning:
			"Sensor fault. Wrong sensor type configured, sensor cable unplugged or damaged, or the wrong sensor connected.",
		steps: [
			"Reseat the motor on the Flex dock, or the sensor cable if an external motor is used.",
			"Check the cable for damage. Swap it.",
			"In the REV Hardware Client, confirm the sensor type matches the motor.",
			"Power cycle.",
			"If it persists with a known good motor, swap the controller.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.12v-missing": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and blue slow blink",
		meaning: "No 12 V on the power input. The controller is powered only by USB and will not drive the motor.",
		steps: [
			"Check the power leads at the PDP or PDH and the breaker.",
			"Check the connector at the controller.",
			"On the bench over USB this is expected.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.gate-driver-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and cyan slow blink",
		meaning: "Internal motor drive circuit fault.",
		steps: ["Power cycle.", "If it comes back, swap the controller. REV asks you to contact them if it persists."],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.can-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and yellow slow blink",
		meaning: "The controller sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wires at this controller and its neighbours.",
			"Check termination at the end of the bus.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.temperature-fault": {
		device: "SPARK Flex",
		led: "Status",
		state: "Orange and green slow blink",
		meaning:
			"Temperature cutoff. The controller or motor overheated and output is cut. It clears on its own after cooling.",
		steps: [
			"Let it cool. Do not enable until the blink stops.",
			"Check for a stalled or binding mechanism.",
			"Have the team add or lower current limits in code.",
			"Check airflow around the motor and controller.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.fault-modes.corrupt-firmware": {
		device: "SPARK Flex",
		led: "Status",
		state: "Dark",
		meaning: "Firmware failed to load. The LED stays dark even with power.",
		steps: [
			"Confirm 12 V is present. A dark LED is also just no power.",
			"Enter Recovery Mode: hold the Mode button while plugging in USB, then reflash firmware in the REV Hardware Client.",
			"If it will not take firmware, swap the controller.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.identify": {
		device: "SPARK Flex",
		led: "Status",
		state: "White and magenta fast blink",
		meaning: "Someone pressed Identify in the REV Hardware Client. Cosmetic.",
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.can-firmware-updating": {
		device: "SPARK Flex",
		led: "Status",
		state: "White and yellow blink",
		meaning: "Firmware is being written over CAN.",
		steps: [
			"Do not power off. Wait for it to finish.",
			"If it sits there for minutes, power cycle and update over USB instead.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.can-firmware-retry": {
		device: "SPARK Flex",
		led: "Status",
		state: "White and blue blink",
		meaning: "A CAN firmware update failed and the controller is retrying.",
		steps: ["Keep power on and let it retry.", "If it stays here, update over USB with the REV Hardware Client."],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.usb-device-firmware-update": {
		device: "SPARK Flex",
		led: "Status",
		state: "Dark",
		meaning: "USB firmware update mode. The REV Hardware Client is flashing it.",
		steps: ["Finish the update in the Hardware Client, then power cycle."],
		source: REV_FLEX,
	},
	"revsparkflex.identification-updating-and-recovery.recovery-mode": {
		device: "SPARK Flex",
		led: "Status",
		state: "Dark",
		meaning: "Recovery mode. Used to reflash a controller whose firmware is corrupt.",
		steps: ["Connect USB and flash firmware in the REV Hardware Client.", "Power cycle when done."],
		source: REV_FLEX,
	},
	"revsparkflex.movement.partial-forward": {
		device: "SPARK Flex",
		led: "Status",
		state: "Green blink",
		meaning: "Driving forward at partial output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.full-forward": {
		device: "SPARK Flex",
		led: "Status",
		state: "Green solid",
		meaning: "Driving forward at full output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.partial-reverse": {
		device: "SPARK Flex",
		led: "Status",
		state: "Red blink",
		meaning: "Driving reverse at partial output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.full-reverse": {
		device: "SPARK Flex",
		led: "Status",
		state: "Red solid",
		meaning: "Driving reverse at full output.",
		source: REV_FLEX,
	},
	"revsparkflex.movement.forward-limit": {
		device: "SPARK Flex",
		led: "Status",
		state: "Green and white blink",
		meaning: "The forward limit switch or soft limit is active. Forward output is blocked.",
		steps: [
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			"Move the mechanism off the limit.",
		],
		source: REV_FLEX,
	},
	"revsparkflex.movement.reverse-limit": {
		device: "SPARK Flex",
		led: "Status",
		state: "Red and white blink",
		meaning: "The reverse limit switch or soft limit is active. Reverse output is blocked.",
		steps: [
			"Check the limit switch and its wiring at the data port. A disconnected normally closed switch reads as pressed.",
			"In the REV Hardware Client, check the limit switch polarity setting.",
			"Move the mechanism off the limit.",
		],
		source: REV_FLEX,
	},
	"revpowerdistributionhub.general-status.no-communication-established": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Blue solid",
		meaning: "Powered, no CAN communication yet. Normal for the first seconds after boot.",
		steps: [
			"Wait for the roboRIO to boot and code to start.",
			"If it stays blue: check the CAN wiring to the PDH and the termination switch on the PDH.",
			"Confirm robot code is running (roboRIO Comm LED green).",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.roborio-communication-established": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Green solid",
		meaning: "Communicating with the roboRIO. Normal.",
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.connected-to-rev-hardware-client": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Cyan solid",
		meaning: "A laptop running the REV Hardware Client is connected over USB-C. Fine in the pit.",
		steps: ["Unplug the USB cable before the robot goes to the field."],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.keep-alive-timeout": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Magenta blink",
		meaning:
			"The PDH had communication with the roboRIO and lost it. The roboRIO stopped sending heartbeat frames.",
		steps: [
			"Check whether the roboRIO rebooted or code crashed (Comm LED).",
			"Check the CAN wiring between the roboRIO and the PDH.",
			"Power cycle.",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.low-battery": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and blue blink",
		meaning: "Battery voltage is low.",
		steps: ["Swap the battery.", "Check the main battery connections and main breaker for heat or looseness."],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.can-fault": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and yellow blink",
		meaning: "The PDH sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wiring at the PDH and its neighbours.",
			"Check the termination switch on the PDH. It must be on if the PDH is the end of the bus, off if not.",
			"Look for a duplicate CAN ID in the REV Hardware Client.",
			"Power cycle.",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.hardware-fault": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and cyan blink",
		meaning: "The PDH detected an internal hardware fault.",
		steps: ["Power cycle.", "Inspect for metal debris and damage.", "If it comes back, swap the PDH."],
		source: REV_PDH,
	},
	"revpowerdistributionhub.general-status.device-over-current": {
		device: "Power Distribution Hub",
		led: "Status",
		state: "Orange and magenta blink",
		meaning: "The PDH itself is over its current limit.",
		steps: [
			"Look for a shorted channel or a stalled motor.",
			"Reduce load.",
			"Check the main breaker and battery leads.",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.channel-status.has-voltage-and-normal-operation": {
		device: "Power Distribution Hub",
		led: "Channel",
		state: "Off",
		meaning: "The channel has voltage and no fault. Normal.",
		source: REV_PDH,
	},
	"revpowerdistributionhub.channel-status.no-voltage-and-active-fault": {
		device: "Power Distribution Hub",
		led: "Channel",
		state: "Red solid",
		meaning: "The channel has no output voltage. The breaker is tripped, missing, or not seated.",
		steps: [
			"Press the breaker back in and check it is seated.",
			"Swap the breaker.",
			"Check the load on that channel for a short.",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.channel-status.sticky-fault": {
		device: "Power Distribution Hub",
		led: "Channel",
		state: "Red blink",
		meaning: "A fault happened earlier on this channel and has not been cleared. The channel may be working now.",
		steps: [
			"Check the breaker is seated.",
			"Clear sticky faults from the REV Hardware Client or from code.",
			"If it comes back, find the intermittent short or the tripping breaker on that channel.",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.switched-channel.has-voltage-and-normal-operation": {
		device: "Power Distribution Hub",
		led: "Switched channel",
		state: "Off",
		meaning: "The switched channel has voltage and no fault. Normal.",
		source: REV_PDH,
	},
	"revpowerdistributionhub.switched-channel.no-voltage-and-active-fault": {
		device: "Power Distribution Hub",
		led: "Switched channel",
		state: "Red solid",
		meaning: "The switched channel has no output voltage. The fuse is blown or missing.",
		steps: [
			"Check the fuse is present and seated.",
			"Replace the fuse.",
			"Check the load for a short before replacing again.",
		],
		source: REV_PDH,
	},
	"revpowerdistributionhub.switched-channel.sticky-fault": {
		device: "Power Distribution Hub",
		led: "Switched channel",
		state: "Red blink",
		meaning: "A fault happened earlier on the switched channel and has not been cleared.",
		steps: ["Check the fuse.", "Clear sticky faults from the REV Hardware Client or from code."],
		source: REV_PDH,
	},
	"revpneumaticshub.general-status.no-communication-established": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Blue solid",
		meaning: "Powered, no CAN communication yet. Normal for the first seconds after boot.",
		steps: [
			"Wait for the roboRIO to boot and code to start.",
			"If it stays blue: check the CAN wiring to the hub and the termination switch.",
			"Confirm the code creates a pneumatics object for the REV hub type.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.roborio-communication-established": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Green solid",
		meaning: "Communicating with the roboRIO. Normal.",
		source: REV_PH,
	},
	"revpneumaticshub.general-status.secondary-heartbeat": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Cyan solid",
		meaning: "A laptop running the REV Hardware Client is connected over USB-C. Fine in the pit.",
		steps: ["Unplug the USB cable before the robot goes to the field."],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.keep-alive-timeout": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Magenta blink",
		meaning: "The hub had communication with the roboRIO and lost it.",
		steps: [
			"Check whether the roboRIO rebooted or code crashed (Comm LED).",
			"Check the CAN wiring to the hub.",
			"Power cycle.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.hardware-fault": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and cyan blink",
		meaning: "The hub detected an internal hardware fault.",
		steps: ["Power cycle.", "Inspect for metal debris and damage.", "If it comes back, swap the hub."],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.can-fault": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and yellow blink",
		meaning: "The hub sees a problem on the CAN bus.",
		steps: [
			"Check the CAN wiring at the hub and its neighbours.",
			"Check the termination switch.",
			"Look for a duplicate CAN ID.",
			"Power cycle.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.compressor-over-current": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and green blink",
		meaning: "The compressor output is drawing too much current.",
		steps: [
			"Check the compressor wiring for a short.",
			"Check the compressor turns freely and is not seized.",
			"Let it cool, then power cycle.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.general-status.device-over-current": {
		device: "Pneumatic Hub",
		led: "Status",
		state: "Orange and magenta blink",
		meaning: "The hub is over its current limit, usually on a solenoid output.",
		steps: [
			"Unplug solenoids one at a time to find the shorted one.",
			"Check solenoid voltage setting matches the solenoids (12 V or 24 V).",
			"Power cycle.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.compressor-status.compressor-off": {
		device: "Pneumatic Hub",
		led: "Compressor",
		state: "Off",
		meaning: "The compressor output is off.",
		steps: [
			"Normal when the system is at pressure or the robot is disabled.",
			"If the compressor should run: check the pressure switch wiring and that code enables the compressor.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.compressor-status.compressor-on": {
		device: "Pneumatic Hub",
		led: "Compressor",
		state: "Green solid",
		meaning: "The compressor output is on.",
		steps: [
			"If the compressor is not running with this on, check the compressor wiring and the compressor itself.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.solenoid-status.solenoid-off": {
		device: "Pneumatic Hub",
		led: "Solenoid",
		state: "Off",
		meaning: "That solenoid channel is not energized.",
		steps: [
			"Normal when the solenoid is commanded off.",
			"If it should be on, the problem is in code or the channel number.",
		],
		source: REV_PH,
	},
	"revpneumaticshub.solenoid-status.solenoid-on": {
		device: "Pneumatic Hub",
		led: "Solenoid",
		state: "Green solid",
		meaning: "That solenoid channel is energized.",
		steps: [
			"If the cylinder does not move: check air pressure, the solenoid wiring, and the solenoid voltage setting.",
		],
		source: REV_PH,
	},
} as const satisfies Record<string, StatusLightHelp>;
