"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.READY_FOR_POST_RESULT = exports.MATCH_OVER = exports.MATCH_ABORTED = exports.READY_TO_PRESTART = exports.PRESTART_INITIATED = exports.PRESTART_COMPLETED = exports.MATCH_READY = exports.MATCH_RUNNING_AUTO = exports.MATCH_TRANSITIONING = exports.MATCH_RUNNING_TELEOP = exports.UNKNOWN = exports.CODE = exports.NO_CODE = exports.ESTOP = exports.BYPASS = exports.WRONG_MATCH = exports.MOVE_STATION = exports.GREEN_X = exports.GREEN = exports.RED = void 0;
exports.RED = 0;
exports.GREEN = 1;
exports.GREEN_X = 2;
exports.MOVE_STATION = 3;
exports.WRONG_MATCH = 4;
exports.BYPASS = 5;
exports.ESTOP = 6;
exports.NO_CODE = 0;
exports.CODE = 1;
exports.UNKNOWN = 0;
exports.MATCH_RUNNING_TELEOP = 1;
exports.MATCH_TRANSITIONING = 2;
exports.MATCH_RUNNING_AUTO = 3;
exports.MATCH_READY = 4;
exports.PRESTART_COMPLETED = 5;
exports.PRESTART_INITIATED = 6;
exports.READY_TO_PRESTART = 7;
exports.MATCH_ABORTED = 8;
exports.MATCH_OVER = 9;
exports.READY_FOR_POST_RESULT = 10;
